// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	FriendRequests  string
	Friendships     string
	Images          string
	ImagesThings    string
	Lists           string
	ListsThings     string
	Properties      string
	QuantityEntries string
	Shares          string
	SharesLists     string
	SharesThings    string
	Things          string
	Users           string
}{
	FriendRequests:  "friend_requests",
	Friendships:     "friendships",
	Images:          "images",
	ImagesThings:    "images_things",
	Lists:           "lists",
	ListsThings:     "lists_things",
	Properties:      "properties",
	QuantityEntries: "quantity_entries",
	Shares:          "shares",
	SharesLists:     "shares_lists",
	SharesThings:    "shares_things",
	Things:          "things",
	Users:           "users",
}
