// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	CartEntries            string
	EmailVerificationCodes string
	EmailVerifications     string
	Exports                string
	ExternalAuth           string
	FriendRequests         string
	Friendships            string
	Images                 string
	ImagesThings           string
	Imports                string
	Lists                  string
	ListsThings            string
	Notifications          string
	Profiles               string
	Properties             string
	PublicShares           string
	QuantityEntries        string
	Shares                 string
	SharesLists            string
	SharesThings           string
	Things                 string
	Users                  string
}{
	CartEntries:            "cart_entries",
	EmailVerificationCodes: "email_verification_codes",
	EmailVerifications:     "email_verifications",
	Exports:                "exports",
	ExternalAuth:           "external_auth",
	FriendRequests:         "friend_requests",
	Friendships:            "friendships",
	Images:                 "images",
	ImagesThings:           "images_things",
	Imports:                "imports",
	Lists:                  "lists",
	ListsThings:            "lists_things",
	Notifications:          "notifications",
	Profiles:               "profiles",
	Properties:             "properties",
	PublicShares:           "public_shares",
	QuantityEntries:        "quantity_entries",
	Shares:                 "shares",
	SharesLists:            "shares_lists",
	SharesThings:           "shares_things",
	Things:                 "things",
	Users:                  "users",
}
