// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// EmailVerificationCode is an object representing the database table.
type EmailVerificationCode struct {
	UserID     string    `boil:"user_id" json:"user_id" toml:"user_id" yaml:"user_id"`
	Email      string    `boil:"email" json:"email" toml:"email" yaml:"email"`
	DigitCode  string    `boil:"digit_code" json:"digit_code" toml:"digit_code" yaml:"digit_code"`
	ValidUntil time.Time `boil:"valid_until" json:"valid_until" toml:"valid_until" yaml:"valid_until"`

	R *emailVerificationCodeR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L emailVerificationCodeL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var EmailVerificationCodeColumns = struct {
	UserID     string
	Email      string
	DigitCode  string
	ValidUntil string
}{
	UserID:     "user_id",
	Email:      "email",
	DigitCode:  "digit_code",
	ValidUntil: "valid_until",
}

var EmailVerificationCodeTableColumns = struct {
	UserID     string
	Email      string
	DigitCode  string
	ValidUntil string
}{
	UserID:     "email_verification_codes.user_id",
	Email:      "email_verification_codes.email",
	DigitCode:  "email_verification_codes.digit_code",
	ValidUntil: "email_verification_codes.valid_until",
}

// Generated where

var EmailVerificationCodeWhere = struct {
	UserID     whereHelperstring
	Email      whereHelperstring
	DigitCode  whereHelperstring
	ValidUntil whereHelpertime_Time
}{
	UserID:     whereHelperstring{field: "\"email_verification_codes\".\"user_id\""},
	Email:      whereHelperstring{field: "\"email_verification_codes\".\"email\""},
	DigitCode:  whereHelperstring{field: "\"email_verification_codes\".\"digit_code\""},
	ValidUntil: whereHelpertime_Time{field: "\"email_verification_codes\".\"valid_until\""},
}

// EmailVerificationCodeRels is where relationship names are stored.
var EmailVerificationCodeRels = struct {
	User string
}{
	User: "User",
}

// emailVerificationCodeR is where relationships are stored.
type emailVerificationCodeR struct {
	User *User `boil:"User" json:"User" toml:"User" yaml:"User"`
}

// NewStruct creates a new relationship struct
func (*emailVerificationCodeR) NewStruct() *emailVerificationCodeR {
	return &emailVerificationCodeR{}
}

func (o *EmailVerificationCode) GetUser() *User {
	if o == nil {
		return nil
	}

	return o.R.GetUser()
}

func (r *emailVerificationCodeR) GetUser() *User {
	if r == nil {
		return nil
	}

	return r.User
}

// emailVerificationCodeL is where Load methods for each relationship are stored.
type emailVerificationCodeL struct{}

var (
	emailVerificationCodeAllColumns            = []string{"user_id", "email", "digit_code", "valid_until"}
	emailVerificationCodeColumnsWithoutDefault = []string{"user_id", "email", "digit_code", "valid_until"}
	emailVerificationCodeColumnsWithDefault    = []string{}
	emailVerificationCodePrimaryKeyColumns     = []string{"user_id", "email", "digit_code"}
	emailVerificationCodeGeneratedColumns      = []string{}
)

type (
	// EmailVerificationCodeSlice is an alias for a slice of pointers to EmailVerificationCode.
	// This should almost always be used instead of []EmailVerificationCode.
	EmailVerificationCodeSlice []*EmailVerificationCode
	// EmailVerificationCodeHook is the signature for custom EmailVerificationCode hook methods
	EmailVerificationCodeHook func(context.Context, boil.ContextExecutor, *EmailVerificationCode) error

	emailVerificationCodeQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	emailVerificationCodeType                 = reflect.TypeOf(&EmailVerificationCode{})
	emailVerificationCodeMapping              = queries.MakeStructMapping(emailVerificationCodeType)
	emailVerificationCodePrimaryKeyMapping, _ = queries.BindMapping(emailVerificationCodeType, emailVerificationCodeMapping, emailVerificationCodePrimaryKeyColumns)
	emailVerificationCodeInsertCacheMut       sync.RWMutex
	emailVerificationCodeInsertCache          = make(map[string]insertCache)
	emailVerificationCodeUpdateCacheMut       sync.RWMutex
	emailVerificationCodeUpdateCache          = make(map[string]updateCache)
	emailVerificationCodeUpsertCacheMut       sync.RWMutex
	emailVerificationCodeUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var emailVerificationCodeAfterSelectMu sync.Mutex
var emailVerificationCodeAfterSelectHooks []EmailVerificationCodeHook

var emailVerificationCodeBeforeInsertMu sync.Mutex
var emailVerificationCodeBeforeInsertHooks []EmailVerificationCodeHook
var emailVerificationCodeAfterInsertMu sync.Mutex
var emailVerificationCodeAfterInsertHooks []EmailVerificationCodeHook

var emailVerificationCodeBeforeUpdateMu sync.Mutex
var emailVerificationCodeBeforeUpdateHooks []EmailVerificationCodeHook
var emailVerificationCodeAfterUpdateMu sync.Mutex
var emailVerificationCodeAfterUpdateHooks []EmailVerificationCodeHook

var emailVerificationCodeBeforeDeleteMu sync.Mutex
var emailVerificationCodeBeforeDeleteHooks []EmailVerificationCodeHook
var emailVerificationCodeAfterDeleteMu sync.Mutex
var emailVerificationCodeAfterDeleteHooks []EmailVerificationCodeHook

var emailVerificationCodeBeforeUpsertMu sync.Mutex
var emailVerificationCodeBeforeUpsertHooks []EmailVerificationCodeHook
var emailVerificationCodeAfterUpsertMu sync.Mutex
var emailVerificationCodeAfterUpsertHooks []EmailVerificationCodeHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *EmailVerificationCode) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range emailVerificationCodeAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *EmailVerificationCode) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range emailVerificationCodeBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *EmailVerificationCode) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range emailVerificationCodeAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *EmailVerificationCode) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range emailVerificationCodeBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *EmailVerificationCode) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range emailVerificationCodeAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *EmailVerificationCode) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range emailVerificationCodeBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *EmailVerificationCode) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range emailVerificationCodeAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *EmailVerificationCode) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range emailVerificationCodeBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *EmailVerificationCode) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range emailVerificationCodeAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddEmailVerificationCodeHook registers your hook function for all future operations.
func AddEmailVerificationCodeHook(hookPoint boil.HookPoint, emailVerificationCodeHook EmailVerificationCodeHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		emailVerificationCodeAfterSelectMu.Lock()
		emailVerificationCodeAfterSelectHooks = append(emailVerificationCodeAfterSelectHooks, emailVerificationCodeHook)
		emailVerificationCodeAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		emailVerificationCodeBeforeInsertMu.Lock()
		emailVerificationCodeBeforeInsertHooks = append(emailVerificationCodeBeforeInsertHooks, emailVerificationCodeHook)
		emailVerificationCodeBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		emailVerificationCodeAfterInsertMu.Lock()
		emailVerificationCodeAfterInsertHooks = append(emailVerificationCodeAfterInsertHooks, emailVerificationCodeHook)
		emailVerificationCodeAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		emailVerificationCodeBeforeUpdateMu.Lock()
		emailVerificationCodeBeforeUpdateHooks = append(emailVerificationCodeBeforeUpdateHooks, emailVerificationCodeHook)
		emailVerificationCodeBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		emailVerificationCodeAfterUpdateMu.Lock()
		emailVerificationCodeAfterUpdateHooks = append(emailVerificationCodeAfterUpdateHooks, emailVerificationCodeHook)
		emailVerificationCodeAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		emailVerificationCodeBeforeDeleteMu.Lock()
		emailVerificationCodeBeforeDeleteHooks = append(emailVerificationCodeBeforeDeleteHooks, emailVerificationCodeHook)
		emailVerificationCodeBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		emailVerificationCodeAfterDeleteMu.Lock()
		emailVerificationCodeAfterDeleteHooks = append(emailVerificationCodeAfterDeleteHooks, emailVerificationCodeHook)
		emailVerificationCodeAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		emailVerificationCodeBeforeUpsertMu.Lock()
		emailVerificationCodeBeforeUpsertHooks = append(emailVerificationCodeBeforeUpsertHooks, emailVerificationCodeHook)
		emailVerificationCodeBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		emailVerificationCodeAfterUpsertMu.Lock()
		emailVerificationCodeAfterUpsertHooks = append(emailVerificationCodeAfterUpsertHooks, emailVerificationCodeHook)
		emailVerificationCodeAfterUpsertMu.Unlock()
	}
}

// One returns a single emailVerificationCode record from the query.
func (q emailVerificationCodeQuery) One(ctx context.Context, exec boil.ContextExecutor) (*EmailVerificationCode, error) {
	o := &EmailVerificationCode{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for email_verification_codes")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all EmailVerificationCode records from the query.
func (q emailVerificationCodeQuery) All(ctx context.Context, exec boil.ContextExecutor) (EmailVerificationCodeSlice, error) {
	var o []*EmailVerificationCode

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to EmailVerificationCode slice")
	}

	if len(emailVerificationCodeAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all EmailVerificationCode records in the query.
func (q emailVerificationCodeQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count email_verification_codes rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q emailVerificationCodeQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if email_verification_codes exists")
	}

	return count > 0, nil
}

// User pointed to by the foreign key.
func (o *EmailVerificationCode) User(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.UserID),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// LoadUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (emailVerificationCodeL) LoadUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeEmailVerificationCode interface{}, mods queries.Applicator) error {
	var slice []*EmailVerificationCode
	var object *EmailVerificationCode

	if singular {
		var ok bool
		object, ok = maybeEmailVerificationCode.(*EmailVerificationCode)
		if !ok {
			object = new(EmailVerificationCode)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeEmailVerificationCode)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeEmailVerificationCode))
			}
		}
	} else {
		s, ok := maybeEmailVerificationCode.(*[]*EmailVerificationCode)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeEmailVerificationCode)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeEmailVerificationCode))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &emailVerificationCodeR{}
		}
		args[object.UserID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &emailVerificationCodeR{}
			}

			args[obj.UserID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(userAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.User = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.EmailVerificationCodes = append(foreign.R.EmailVerificationCodes, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.UserID == foreign.ID {
				local.R.User = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.EmailVerificationCodes = append(foreign.R.EmailVerificationCodes, local)
				break
			}
		}
	}

	return nil
}

// SetUser of the emailVerificationCode to the related item.
// Sets o.R.User to related.
// Adds o to related.R.EmailVerificationCodes.
func (o *EmailVerificationCode) SetUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"email_verification_codes\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"user_id"}),
		strmangle.WhereClause("\"", "\"", 2, emailVerificationCodePrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.UserID, o.Email, o.DigitCode}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.UserID = related.ID
	if o.R == nil {
		o.R = &emailVerificationCodeR{
			User: related,
		}
	} else {
		o.R.User = related
	}

	if related.R == nil {
		related.R = &userR{
			EmailVerificationCodes: EmailVerificationCodeSlice{o},
		}
	} else {
		related.R.EmailVerificationCodes = append(related.R.EmailVerificationCodes, o)
	}

	return nil
}

// EmailVerificationCodes retrieves all the records using an executor.
func EmailVerificationCodes(mods ...qm.QueryMod) emailVerificationCodeQuery {
	mods = append(mods, qm.From("\"email_verification_codes\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"email_verification_codes\".*"})
	}

	return emailVerificationCodeQuery{q}
}

// FindEmailVerificationCode retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindEmailVerificationCode(ctx context.Context, exec boil.ContextExecutor, userID string, email string, digitCode string, selectCols ...string) (*EmailVerificationCode, error) {
	emailVerificationCodeObj := &EmailVerificationCode{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"email_verification_codes\" where \"user_id\"=$1 AND \"email\"=$2 AND \"digit_code\"=$3", sel,
	)

	q := queries.Raw(query, userID, email, digitCode)

	err := q.Bind(ctx, exec, emailVerificationCodeObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from email_verification_codes")
	}

	if err = emailVerificationCodeObj.doAfterSelectHooks(ctx, exec); err != nil {
		return emailVerificationCodeObj, err
	}

	return emailVerificationCodeObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *EmailVerificationCode) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no email_verification_codes provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(emailVerificationCodeColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	emailVerificationCodeInsertCacheMut.RLock()
	cache, cached := emailVerificationCodeInsertCache[key]
	emailVerificationCodeInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			emailVerificationCodeAllColumns,
			emailVerificationCodeColumnsWithDefault,
			emailVerificationCodeColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(emailVerificationCodeType, emailVerificationCodeMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(emailVerificationCodeType, emailVerificationCodeMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"email_verification_codes\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"email_verification_codes\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into email_verification_codes")
	}

	if !cached {
		emailVerificationCodeInsertCacheMut.Lock()
		emailVerificationCodeInsertCache[key] = cache
		emailVerificationCodeInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the EmailVerificationCode.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *EmailVerificationCode) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	emailVerificationCodeUpdateCacheMut.RLock()
	cache, cached := emailVerificationCodeUpdateCache[key]
	emailVerificationCodeUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			emailVerificationCodeAllColumns,
			emailVerificationCodePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update email_verification_codes, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"email_verification_codes\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, emailVerificationCodePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(emailVerificationCodeType, emailVerificationCodeMapping, append(wl, emailVerificationCodePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update email_verification_codes row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for email_verification_codes")
	}

	if !cached {
		emailVerificationCodeUpdateCacheMut.Lock()
		emailVerificationCodeUpdateCache[key] = cache
		emailVerificationCodeUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q emailVerificationCodeQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for email_verification_codes")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for email_verification_codes")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o EmailVerificationCodeSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), emailVerificationCodePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"email_verification_codes\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, emailVerificationCodePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in emailVerificationCode slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all emailVerificationCode")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *EmailVerificationCode) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no email_verification_codes provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(emailVerificationCodeColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	emailVerificationCodeUpsertCacheMut.RLock()
	cache, cached := emailVerificationCodeUpsertCache[key]
	emailVerificationCodeUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			emailVerificationCodeAllColumns,
			emailVerificationCodeColumnsWithDefault,
			emailVerificationCodeColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			emailVerificationCodeAllColumns,
			emailVerificationCodePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert email_verification_codes, could not build update column list")
		}

		ret := strmangle.SetComplement(emailVerificationCodeAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(emailVerificationCodePrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert email_verification_codes, could not build conflict column list")
			}

			conflict = make([]string, len(emailVerificationCodePrimaryKeyColumns))
			copy(conflict, emailVerificationCodePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"email_verification_codes\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(emailVerificationCodeType, emailVerificationCodeMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(emailVerificationCodeType, emailVerificationCodeMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert email_verification_codes")
	}

	if !cached {
		emailVerificationCodeUpsertCacheMut.Lock()
		emailVerificationCodeUpsertCache[key] = cache
		emailVerificationCodeUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single EmailVerificationCode record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *EmailVerificationCode) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no EmailVerificationCode provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), emailVerificationCodePrimaryKeyMapping)
	sql := "DELETE FROM \"email_verification_codes\" WHERE \"user_id\"=$1 AND \"email\"=$2 AND \"digit_code\"=$3"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from email_verification_codes")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for email_verification_codes")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q emailVerificationCodeQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no emailVerificationCodeQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from email_verification_codes")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for email_verification_codes")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o EmailVerificationCodeSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(emailVerificationCodeBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), emailVerificationCodePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"email_verification_codes\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, emailVerificationCodePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from emailVerificationCode slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for email_verification_codes")
	}

	if len(emailVerificationCodeAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *EmailVerificationCode) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindEmailVerificationCode(ctx, exec, o.UserID, o.Email, o.DigitCode)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *EmailVerificationCodeSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := EmailVerificationCodeSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), emailVerificationCodePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"email_verification_codes\".* FROM \"email_verification_codes\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, emailVerificationCodePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in EmailVerificationCodeSlice")
	}

	*o = slice

	return nil
}

// EmailVerificationCodeExists checks if the EmailVerificationCode row exists.
func EmailVerificationCodeExists(ctx context.Context, exec boil.ContextExecutor, userID string, email string, digitCode string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"email_verification_codes\" where \"user_id\"=$1 AND \"email\"=$2 AND \"digit_code\"=$3 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, userID, email, digitCode)
	}
	row := exec.QueryRowContext(ctx, sql, userID, email, digitCode)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if email_verification_codes exists")
	}

	return exists, nil
}

// Exists checks if the EmailVerificationCode row exists.
func (o *EmailVerificationCode) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return EmailVerificationCodeExists(ctx, exec, o.UserID, o.Email, o.DigitCode)
}
