// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// ExternalAuth is an object representing the database table.
type ExternalAuth struct {
	UserID   string `boil:"user_id" json:"user_id" toml:"user_id" yaml:"user_id"`
	Provider string `boil:"provider" json:"provider" toml:"provider" yaml:"provider"`
	Subject  string `boil:"subject" json:"subject" toml:"subject" yaml:"subject"`

	R *externalAuthR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L externalAuthL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ExternalAuthColumns = struct {
	UserID   string
	Provider string
	Subject  string
}{
	UserID:   "user_id",
	Provider: "provider",
	Subject:  "subject",
}

var ExternalAuthTableColumns = struct {
	UserID   string
	Provider string
	Subject  string
}{
	UserID:   "external_auth.user_id",
	Provider: "external_auth.provider",
	Subject:  "external_auth.subject",
}

// Generated where

var ExternalAuthWhere = struct {
	UserID   whereHelperstring
	Provider whereHelperstring
	Subject  whereHelperstring
}{
	UserID:   whereHelperstring{field: "\"external_auth\".\"user_id\""},
	Provider: whereHelperstring{field: "\"external_auth\".\"provider\""},
	Subject:  whereHelperstring{field: "\"external_auth\".\"subject\""},
}

// ExternalAuthRels is where relationship names are stored.
var ExternalAuthRels = struct {
	User string
}{
	User: "User",
}

// externalAuthR is where relationships are stored.
type externalAuthR struct {
	User *User `boil:"User" json:"User" toml:"User" yaml:"User"`
}

// NewStruct creates a new relationship struct
func (*externalAuthR) NewStruct() *externalAuthR {
	return &externalAuthR{}
}

func (o *ExternalAuth) GetUser() *User {
	if o == nil {
		return nil
	}

	return o.R.GetUser()
}

func (r *externalAuthR) GetUser() *User {
	if r == nil {
		return nil
	}

	return r.User
}

// externalAuthL is where Load methods for each relationship are stored.
type externalAuthL struct{}

var (
	externalAuthAllColumns            = []string{"user_id", "provider", "subject"}
	externalAuthColumnsWithoutDefault = []string{"user_id", "provider", "subject"}
	externalAuthColumnsWithDefault    = []string{}
	externalAuthPrimaryKeyColumns     = []string{"user_id", "provider"}
	externalAuthGeneratedColumns      = []string{}
)

type (
	// ExternalAuthSlice is an alias for a slice of pointers to ExternalAuth.
	// This should almost always be used instead of []ExternalAuth.
	ExternalAuthSlice []*ExternalAuth
	// ExternalAuthHook is the signature for custom ExternalAuth hook methods
	ExternalAuthHook func(context.Context, boil.ContextExecutor, *ExternalAuth) error

	externalAuthQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	externalAuthType                 = reflect.TypeOf(&ExternalAuth{})
	externalAuthMapping              = queries.MakeStructMapping(externalAuthType)
	externalAuthPrimaryKeyMapping, _ = queries.BindMapping(externalAuthType, externalAuthMapping, externalAuthPrimaryKeyColumns)
	externalAuthInsertCacheMut       sync.RWMutex
	externalAuthInsertCache          = make(map[string]insertCache)
	externalAuthUpdateCacheMut       sync.RWMutex
	externalAuthUpdateCache          = make(map[string]updateCache)
	externalAuthUpsertCacheMut       sync.RWMutex
	externalAuthUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var externalAuthAfterSelectMu sync.Mutex
var externalAuthAfterSelectHooks []ExternalAuthHook

var externalAuthBeforeInsertMu sync.Mutex
var externalAuthBeforeInsertHooks []ExternalAuthHook
var externalAuthAfterInsertMu sync.Mutex
var externalAuthAfterInsertHooks []ExternalAuthHook

var externalAuthBeforeUpdateMu sync.Mutex
var externalAuthBeforeUpdateHooks []ExternalAuthHook
var externalAuthAfterUpdateMu sync.Mutex
var externalAuthAfterUpdateHooks []ExternalAuthHook

var externalAuthBeforeDeleteMu sync.Mutex
var externalAuthBeforeDeleteHooks []ExternalAuthHook
var externalAuthAfterDeleteMu sync.Mutex
var externalAuthAfterDeleteHooks []ExternalAuthHook

var externalAuthBeforeUpsertMu sync.Mutex
var externalAuthBeforeUpsertHooks []ExternalAuthHook
var externalAuthAfterUpsertMu sync.Mutex
var externalAuthAfterUpsertHooks []ExternalAuthHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *ExternalAuth) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range externalAuthAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *ExternalAuth) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range externalAuthBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *ExternalAuth) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range externalAuthAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *ExternalAuth) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range externalAuthBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *ExternalAuth) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range externalAuthAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *ExternalAuth) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range externalAuthBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *ExternalAuth) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range externalAuthAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *ExternalAuth) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range externalAuthBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *ExternalAuth) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range externalAuthAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddExternalAuthHook registers your hook function for all future operations.
func AddExternalAuthHook(hookPoint boil.HookPoint, externalAuthHook ExternalAuthHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		externalAuthAfterSelectMu.Lock()
		externalAuthAfterSelectHooks = append(externalAuthAfterSelectHooks, externalAuthHook)
		externalAuthAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		externalAuthBeforeInsertMu.Lock()
		externalAuthBeforeInsertHooks = append(externalAuthBeforeInsertHooks, externalAuthHook)
		externalAuthBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		externalAuthAfterInsertMu.Lock()
		externalAuthAfterInsertHooks = append(externalAuthAfterInsertHooks, externalAuthHook)
		externalAuthAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		externalAuthBeforeUpdateMu.Lock()
		externalAuthBeforeUpdateHooks = append(externalAuthBeforeUpdateHooks, externalAuthHook)
		externalAuthBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		externalAuthAfterUpdateMu.Lock()
		externalAuthAfterUpdateHooks = append(externalAuthAfterUpdateHooks, externalAuthHook)
		externalAuthAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		externalAuthBeforeDeleteMu.Lock()
		externalAuthBeforeDeleteHooks = append(externalAuthBeforeDeleteHooks, externalAuthHook)
		externalAuthBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		externalAuthAfterDeleteMu.Lock()
		externalAuthAfterDeleteHooks = append(externalAuthAfterDeleteHooks, externalAuthHook)
		externalAuthAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		externalAuthBeforeUpsertMu.Lock()
		externalAuthBeforeUpsertHooks = append(externalAuthBeforeUpsertHooks, externalAuthHook)
		externalAuthBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		externalAuthAfterUpsertMu.Lock()
		externalAuthAfterUpsertHooks = append(externalAuthAfterUpsertHooks, externalAuthHook)
		externalAuthAfterUpsertMu.Unlock()
	}
}

// One returns a single externalAuth record from the query.
func (q externalAuthQuery) One(ctx context.Context, exec boil.ContextExecutor) (*ExternalAuth, error) {
	o := &ExternalAuth{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for external_auth")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all ExternalAuth records from the query.
func (q externalAuthQuery) All(ctx context.Context, exec boil.ContextExecutor) (ExternalAuthSlice, error) {
	var o []*ExternalAuth

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to ExternalAuth slice")
	}

	if len(externalAuthAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all ExternalAuth records in the query.
func (q externalAuthQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count external_auth rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q externalAuthQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if external_auth exists")
	}

	return count > 0, nil
}

// User pointed to by the foreign key.
func (o *ExternalAuth) User(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.UserID),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// LoadUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (externalAuthL) LoadUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeExternalAuth any, mods queries.Applicator) error {
	var slice []*ExternalAuth
	var object *ExternalAuth

	if singular {
		var ok bool
		object, ok = maybeExternalAuth.(*ExternalAuth)
		if !ok {
			object = new(ExternalAuth)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeExternalAuth)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeExternalAuth))
			}
		}
	} else {
		s, ok := maybeExternalAuth.(*[]*ExternalAuth)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeExternalAuth)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeExternalAuth))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &externalAuthR{}
		}
		args[object.UserID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &externalAuthR{}
			}

			args[obj.UserID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(userAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.User = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.ExternalAuths = append(foreign.R.ExternalAuths, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.UserID == foreign.ID {
				local.R.User = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.ExternalAuths = append(foreign.R.ExternalAuths, local)
				break
			}
		}
	}

	return nil
}

// SetUser of the externalAuth to the related item.
// Sets o.R.User to related.
// Adds o to related.R.ExternalAuths.
func (o *ExternalAuth) SetUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"external_auth\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"user_id"}),
		strmangle.WhereClause("\"", "\"", 2, externalAuthPrimaryKeyColumns),
	)
	values := []any{related.ID, o.UserID, o.Provider}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.UserID = related.ID
	if o.R == nil {
		o.R = &externalAuthR{
			User: related,
		}
	} else {
		o.R.User = related
	}

	if related.R == nil {
		related.R = &userR{
			ExternalAuths: ExternalAuthSlice{o},
		}
	} else {
		related.R.ExternalAuths = append(related.R.ExternalAuths, o)
	}

	return nil
}

// ExternalAuths retrieves all the records using an executor.
func ExternalAuths(mods ...qm.QueryMod) externalAuthQuery {
	mods = append(mods, qm.From("\"external_auth\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"external_auth\".*"})
	}

	return externalAuthQuery{q}
}

// FindExternalAuth retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindExternalAuth(ctx context.Context, exec boil.ContextExecutor, userID string, provider string, selectCols ...string) (*ExternalAuth, error) {
	externalAuthObj := &ExternalAuth{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"external_auth\" where \"user_id\"=$1 AND \"provider\"=$2", sel,
	)

	q := queries.Raw(query, userID, provider)

	err := q.Bind(ctx, exec, externalAuthObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from external_auth")
	}

	if err = externalAuthObj.doAfterSelectHooks(ctx, exec); err != nil {
		return externalAuthObj, err
	}

	return externalAuthObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *ExternalAuth) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no external_auth provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(externalAuthColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	externalAuthInsertCacheMut.RLock()
	cache, cached := externalAuthInsertCache[key]
	externalAuthInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			externalAuthAllColumns,
			externalAuthColumnsWithDefault,
			externalAuthColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(externalAuthType, externalAuthMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(externalAuthType, externalAuthMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"external_auth\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"external_auth\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into external_auth")
	}

	if !cached {
		externalAuthInsertCacheMut.Lock()
		externalAuthInsertCache[key] = cache
		externalAuthInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the ExternalAuth.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *ExternalAuth) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	externalAuthUpdateCacheMut.RLock()
	cache, cached := externalAuthUpdateCache[key]
	externalAuthUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			externalAuthAllColumns,
			externalAuthPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update external_auth, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"external_auth\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, externalAuthPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(externalAuthType, externalAuthMapping, append(wl, externalAuthPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update external_auth row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for external_auth")
	}

	if !cached {
		externalAuthUpdateCacheMut.Lock()
		externalAuthUpdateCache[key] = cache
		externalAuthUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q externalAuthQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for external_auth")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for external_auth")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ExternalAuthSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), externalAuthPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"external_auth\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, externalAuthPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in externalAuth slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all externalAuth")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *ExternalAuth) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no external_auth provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(externalAuthColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	externalAuthUpsertCacheMut.RLock()
	cache, cached := externalAuthUpsertCache[key]
	externalAuthUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			externalAuthAllColumns,
			externalAuthColumnsWithDefault,
			externalAuthColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			externalAuthAllColumns,
			externalAuthPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert external_auth, could not build update column list")
		}

		ret := strmangle.SetComplement(externalAuthAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(externalAuthPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert external_auth, could not build conflict column list")
			}

			conflict = make([]string, len(externalAuthPrimaryKeyColumns))
			copy(conflict, externalAuthPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"external_auth\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(externalAuthType, externalAuthMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(externalAuthType, externalAuthMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert external_auth")
	}

	if !cached {
		externalAuthUpsertCacheMut.Lock()
		externalAuthUpsertCache[key] = cache
		externalAuthUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single ExternalAuth record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *ExternalAuth) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no ExternalAuth provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), externalAuthPrimaryKeyMapping)
	sql := "DELETE FROM \"external_auth\" WHERE \"user_id\"=$1 AND \"provider\"=$2"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from external_auth")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for external_auth")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q externalAuthQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no externalAuthQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from external_auth")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for external_auth")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ExternalAuthSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(externalAuthBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), externalAuthPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"external_auth\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, externalAuthPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from externalAuth slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for external_auth")
	}

	if len(externalAuthAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *ExternalAuth) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindExternalAuth(ctx, exec, o.UserID, o.Provider)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ExternalAuthSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ExternalAuthSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), externalAuthPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"external_auth\".* FROM \"external_auth\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, externalAuthPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in ExternalAuthSlice")
	}

	*o = slice

	return nil
}

// ExternalAuthExists checks if the ExternalAuth row exists.
func ExternalAuthExists(ctx context.Context, exec boil.ContextExecutor, userID string, provider string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"external_auth\" where \"user_id\"=$1 AND \"provider\"=$2 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, userID, provider)
	}
	row := exec.QueryRowContext(ctx, sql, userID, provider)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if external_auth exists")
	}

	return exists, nil
}

// Exists checks if the ExternalAuth row exists.
func (o *ExternalAuth) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return ExternalAuthExists(ctx, exec, o.UserID, o.Provider)
}
