// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// FriendRequest is an object representing the database table.
type FriendRequest struct {
	ID         string             `boil:"id" json:"id" toml:"id" yaml:"id"`
	SenderID   string             `boil:"sender_id" json:"sender_id" toml:"sender_id" yaml:"sender_id"`
	ReceiverID string             `boil:"receiver_id" json:"receiver_id" toml:"receiver_id" yaml:"receiver_id"`
	State      FriendRequestState `boil:"state" json:"state" toml:"state" yaml:"state"`
	CreatedAt  time.Time          `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`

	R *friendRequestR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L friendRequestL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var FriendRequestColumns = struct {
	ID         string
	SenderID   string
	ReceiverID string
	State      string
	CreatedAt  string
}{
	ID:         "id",
	SenderID:   "sender_id",
	ReceiverID: "receiver_id",
	State:      "state",
	CreatedAt:  "created_at",
}

var FriendRequestTableColumns = struct {
	ID         string
	SenderID   string
	ReceiverID string
	State      string
	CreatedAt  string
}{
	ID:         "friend_requests.id",
	SenderID:   "friend_requests.sender_id",
	ReceiverID: "friend_requests.receiver_id",
	State:      "friend_requests.state",
	CreatedAt:  "friend_requests.created_at",
}

// Generated where

type whereHelperFriendRequestState struct{ field string }

func (w whereHelperFriendRequestState) EQ(x FriendRequestState) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelperFriendRequestState) NEQ(x FriendRequestState) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelperFriendRequestState) LT(x FriendRequestState) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelperFriendRequestState) LTE(x FriendRequestState) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelperFriendRequestState) GT(x FriendRequestState) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelperFriendRequestState) GTE(x FriendRequestState) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}
func (w whereHelperFriendRequestState) IN(slice []FriendRequestState) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperFriendRequestState) NIN(slice []FriendRequestState) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

var FriendRequestWhere = struct {
	ID         whereHelperstring
	SenderID   whereHelperstring
	ReceiverID whereHelperstring
	State      whereHelperFriendRequestState
	CreatedAt  whereHelpertime_Time
}{
	ID:         whereHelperstring{field: "\"friend_requests\".\"id\""},
	SenderID:   whereHelperstring{field: "\"friend_requests\".\"sender_id\""},
	ReceiverID: whereHelperstring{field: "\"friend_requests\".\"receiver_id\""},
	State:      whereHelperFriendRequestState{field: "\"friend_requests\".\"state\""},
	CreatedAt:  whereHelpertime_Time{field: "\"friend_requests\".\"created_at\""},
}

// FriendRequestRels is where relationship names are stored.
var FriendRequestRels = struct {
	Receiver    string
	Sender      string
	Friendships string
}{
	Receiver:    "Receiver",
	Sender:      "Sender",
	Friendships: "Friendships",
}

// friendRequestR is where relationships are stored.
type friendRequestR struct {
	Receiver    *User           `boil:"Receiver" json:"Receiver" toml:"Receiver" yaml:"Receiver"`
	Sender      *User           `boil:"Sender" json:"Sender" toml:"Sender" yaml:"Sender"`
	Friendships FriendshipSlice `boil:"Friendships" json:"Friendships" toml:"Friendships" yaml:"Friendships"`
}

// NewStruct creates a new relationship struct
func (*friendRequestR) NewStruct() *friendRequestR {
	return &friendRequestR{}
}

func (r *friendRequestR) GetReceiver() *User {
	if r == nil {
		return nil
	}
	return r.Receiver
}

func (r *friendRequestR) GetSender() *User {
	if r == nil {
		return nil
	}
	return r.Sender
}

func (r *friendRequestR) GetFriendships() FriendshipSlice {
	if r == nil {
		return nil
	}
	return r.Friendships
}

// friendRequestL is where Load methods for each relationship are stored.
type friendRequestL struct{}

var (
	friendRequestAllColumns            = []string{"id", "sender_id", "receiver_id", "state", "created_at"}
	friendRequestColumnsWithoutDefault = []string{"id", "sender_id", "receiver_id"}
	friendRequestColumnsWithDefault    = []string{"state", "created_at"}
	friendRequestPrimaryKeyColumns     = []string{"id"}
	friendRequestGeneratedColumns      = []string{}
)

type (
	// FriendRequestSlice is an alias for a slice of pointers to FriendRequest.
	// This should almost always be used instead of []FriendRequest.
	FriendRequestSlice []*FriendRequest
	// FriendRequestHook is the signature for custom FriendRequest hook methods
	FriendRequestHook func(context.Context, boil.ContextExecutor, *FriendRequest) error

	friendRequestQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	friendRequestType                 = reflect.TypeOf(&FriendRequest{})
	friendRequestMapping              = queries.MakeStructMapping(friendRequestType)
	friendRequestPrimaryKeyMapping, _ = queries.BindMapping(friendRequestType, friendRequestMapping, friendRequestPrimaryKeyColumns)
	friendRequestInsertCacheMut       sync.RWMutex
	friendRequestInsertCache          = make(map[string]insertCache)
	friendRequestUpdateCacheMut       sync.RWMutex
	friendRequestUpdateCache          = make(map[string]updateCache)
	friendRequestUpsertCacheMut       sync.RWMutex
	friendRequestUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var friendRequestAfterSelectMu sync.Mutex
var friendRequestAfterSelectHooks []FriendRequestHook

var friendRequestBeforeInsertMu sync.Mutex
var friendRequestBeforeInsertHooks []FriendRequestHook
var friendRequestAfterInsertMu sync.Mutex
var friendRequestAfterInsertHooks []FriendRequestHook

var friendRequestBeforeUpdateMu sync.Mutex
var friendRequestBeforeUpdateHooks []FriendRequestHook
var friendRequestAfterUpdateMu sync.Mutex
var friendRequestAfterUpdateHooks []FriendRequestHook

var friendRequestBeforeDeleteMu sync.Mutex
var friendRequestBeforeDeleteHooks []FriendRequestHook
var friendRequestAfterDeleteMu sync.Mutex
var friendRequestAfterDeleteHooks []FriendRequestHook

var friendRequestBeforeUpsertMu sync.Mutex
var friendRequestBeforeUpsertHooks []FriendRequestHook
var friendRequestAfterUpsertMu sync.Mutex
var friendRequestAfterUpsertHooks []FriendRequestHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *FriendRequest) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range friendRequestAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *FriendRequest) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range friendRequestBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *FriendRequest) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range friendRequestAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *FriendRequest) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range friendRequestBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *FriendRequest) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range friendRequestAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *FriendRequest) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range friendRequestBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *FriendRequest) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range friendRequestAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *FriendRequest) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range friendRequestBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *FriendRequest) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range friendRequestAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddFriendRequestHook registers your hook function for all future operations.
func AddFriendRequestHook(hookPoint boil.HookPoint, friendRequestHook FriendRequestHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		friendRequestAfterSelectMu.Lock()
		friendRequestAfterSelectHooks = append(friendRequestAfterSelectHooks, friendRequestHook)
		friendRequestAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		friendRequestBeforeInsertMu.Lock()
		friendRequestBeforeInsertHooks = append(friendRequestBeforeInsertHooks, friendRequestHook)
		friendRequestBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		friendRequestAfterInsertMu.Lock()
		friendRequestAfterInsertHooks = append(friendRequestAfterInsertHooks, friendRequestHook)
		friendRequestAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		friendRequestBeforeUpdateMu.Lock()
		friendRequestBeforeUpdateHooks = append(friendRequestBeforeUpdateHooks, friendRequestHook)
		friendRequestBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		friendRequestAfterUpdateMu.Lock()
		friendRequestAfterUpdateHooks = append(friendRequestAfterUpdateHooks, friendRequestHook)
		friendRequestAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		friendRequestBeforeDeleteMu.Lock()
		friendRequestBeforeDeleteHooks = append(friendRequestBeforeDeleteHooks, friendRequestHook)
		friendRequestBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		friendRequestAfterDeleteMu.Lock()
		friendRequestAfterDeleteHooks = append(friendRequestAfterDeleteHooks, friendRequestHook)
		friendRequestAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		friendRequestBeforeUpsertMu.Lock()
		friendRequestBeforeUpsertHooks = append(friendRequestBeforeUpsertHooks, friendRequestHook)
		friendRequestBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		friendRequestAfterUpsertMu.Lock()
		friendRequestAfterUpsertHooks = append(friendRequestAfterUpsertHooks, friendRequestHook)
		friendRequestAfterUpsertMu.Unlock()
	}
}

// One returns a single friendRequest record from the query.
func (q friendRequestQuery) One(ctx context.Context, exec boil.ContextExecutor) (*FriendRequest, error) {
	o := &FriendRequest{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for friend_requests")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all FriendRequest records from the query.
func (q friendRequestQuery) All(ctx context.Context, exec boil.ContextExecutor) (FriendRequestSlice, error) {
	var o []*FriendRequest

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to FriendRequest slice")
	}

	if len(friendRequestAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all FriendRequest records in the query.
func (q friendRequestQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count friend_requests rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q friendRequestQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if friend_requests exists")
	}

	return count > 0, nil
}

// Receiver pointed to by the foreign key.
func (o *FriendRequest) Receiver(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.ReceiverID),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// Sender pointed to by the foreign key.
func (o *FriendRequest) Sender(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.SenderID),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// Friendships retrieves all the friendship's Friendships with an executor.
func (o *FriendRequest) Friendships(mods ...qm.QueryMod) friendshipQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"friendships\".\"friend_request_id\"=?", o.ID),
	)

	return Friendships(queryMods...)
}

// LoadReceiver allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (friendRequestL) LoadReceiver(ctx context.Context, e boil.ContextExecutor, singular bool, maybeFriendRequest interface{}, mods queries.Applicator) error {
	var slice []*FriendRequest
	var object *FriendRequest

	if singular {
		var ok bool
		object, ok = maybeFriendRequest.(*FriendRequest)
		if !ok {
			object = new(FriendRequest)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeFriendRequest)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeFriendRequest))
			}
		}
	} else {
		s, ok := maybeFriendRequest.(*[]*FriendRequest)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeFriendRequest)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeFriendRequest))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &friendRequestR{}
		}
		args[object.ReceiverID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &friendRequestR{}
			}

			args[obj.ReceiverID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(userAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Receiver = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.ReceiverFriendRequests = append(foreign.R.ReceiverFriendRequests, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.ReceiverID == foreign.ID {
				local.R.Receiver = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.ReceiverFriendRequests = append(foreign.R.ReceiverFriendRequests, local)
				break
			}
		}
	}

	return nil
}

// LoadSender allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (friendRequestL) LoadSender(ctx context.Context, e boil.ContextExecutor, singular bool, maybeFriendRequest interface{}, mods queries.Applicator) error {
	var slice []*FriendRequest
	var object *FriendRequest

	if singular {
		var ok bool
		object, ok = maybeFriendRequest.(*FriendRequest)
		if !ok {
			object = new(FriendRequest)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeFriendRequest)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeFriendRequest))
			}
		}
	} else {
		s, ok := maybeFriendRequest.(*[]*FriendRequest)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeFriendRequest)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeFriendRequest))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &friendRequestR{}
		}
		args[object.SenderID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &friendRequestR{}
			}

			args[obj.SenderID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(userAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Sender = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.SenderFriendRequests = append(foreign.R.SenderFriendRequests, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.SenderID == foreign.ID {
				local.R.Sender = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.SenderFriendRequests = append(foreign.R.SenderFriendRequests, local)
				break
			}
		}
	}

	return nil
}

// LoadFriendships allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (friendRequestL) LoadFriendships(ctx context.Context, e boil.ContextExecutor, singular bool, maybeFriendRequest interface{}, mods queries.Applicator) error {
	var slice []*FriendRequest
	var object *FriendRequest

	if singular {
		var ok bool
		object, ok = maybeFriendRequest.(*FriendRequest)
		if !ok {
			object = new(FriendRequest)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeFriendRequest)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeFriendRequest))
			}
		}
	} else {
		s, ok := maybeFriendRequest.(*[]*FriendRequest)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeFriendRequest)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeFriendRequest))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &friendRequestR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &friendRequestR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`friendships`),
		qm.WhereIn(`friendships.friend_request_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load friendships")
	}

	var resultSlice []*Friendship
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice friendships")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on friendships")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for friendships")
	}

	if len(friendshipAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.Friendships = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &friendshipR{}
			}
			foreign.R.FriendRequest = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.FriendRequestID {
				local.R.Friendships = append(local.R.Friendships, foreign)
				if foreign.R == nil {
					foreign.R = &friendshipR{}
				}
				foreign.R.FriendRequest = local
				break
			}
		}
	}

	return nil
}

// SetReceiver of the friendRequest to the related item.
// Sets o.R.Receiver to related.
// Adds o to related.R.ReceiverFriendRequests.
func (o *FriendRequest) SetReceiver(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"friend_requests\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"receiver_id"}),
		strmangle.WhereClause("\"", "\"", 2, friendRequestPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.ReceiverID = related.ID
	if o.R == nil {
		o.R = &friendRequestR{
			Receiver: related,
		}
	} else {
		o.R.Receiver = related
	}

	if related.R == nil {
		related.R = &userR{
			ReceiverFriendRequests: FriendRequestSlice{o},
		}
	} else {
		related.R.ReceiverFriendRequests = append(related.R.ReceiverFriendRequests, o)
	}

	return nil
}

// SetSender of the friendRequest to the related item.
// Sets o.R.Sender to related.
// Adds o to related.R.SenderFriendRequests.
func (o *FriendRequest) SetSender(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"friend_requests\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"sender_id"}),
		strmangle.WhereClause("\"", "\"", 2, friendRequestPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.SenderID = related.ID
	if o.R == nil {
		o.R = &friendRequestR{
			Sender: related,
		}
	} else {
		o.R.Sender = related
	}

	if related.R == nil {
		related.R = &userR{
			SenderFriendRequests: FriendRequestSlice{o},
		}
	} else {
		related.R.SenderFriendRequests = append(related.R.SenderFriendRequests, o)
	}

	return nil
}

// AddFriendships adds the given related objects to the existing relationships
// of the friend_request, optionally inserting them as new records.
// Appends related to o.R.Friendships.
// Sets related.R.FriendRequest appropriately.
func (o *FriendRequest) AddFriendships(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Friendship) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.FriendRequestID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"friendships\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"friend_request_id"}),
				strmangle.WhereClause("\"", "\"", 2, friendshipPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.Friend1ID, rel.Friend2ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.FriendRequestID = o.ID
		}
	}

	if o.R == nil {
		o.R = &friendRequestR{
			Friendships: related,
		}
	} else {
		o.R.Friendships = append(o.R.Friendships, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &friendshipR{
				FriendRequest: o,
			}
		} else {
			rel.R.FriendRequest = o
		}
	}
	return nil
}

// FriendRequests retrieves all the records using an executor.
func FriendRequests(mods ...qm.QueryMod) friendRequestQuery {
	mods = append(mods, qm.From("\"friend_requests\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"friend_requests\".*"})
	}

	return friendRequestQuery{q}
}

// FindFriendRequest retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindFriendRequest(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*FriendRequest, error) {
	friendRequestObj := &FriendRequest{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"friend_requests\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, friendRequestObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from friend_requests")
	}

	if err = friendRequestObj.doAfterSelectHooks(ctx, exec); err != nil {
		return friendRequestObj, err
	}

	return friendRequestObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *FriendRequest) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no friend_requests provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(friendRequestColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	friendRequestInsertCacheMut.RLock()
	cache, cached := friendRequestInsertCache[key]
	friendRequestInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			friendRequestAllColumns,
			friendRequestColumnsWithDefault,
			friendRequestColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(friendRequestType, friendRequestMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(friendRequestType, friendRequestMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"friend_requests\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"friend_requests\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into friend_requests")
	}

	if !cached {
		friendRequestInsertCacheMut.Lock()
		friendRequestInsertCache[key] = cache
		friendRequestInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the FriendRequest.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *FriendRequest) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	friendRequestUpdateCacheMut.RLock()
	cache, cached := friendRequestUpdateCache[key]
	friendRequestUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			friendRequestAllColumns,
			friendRequestPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update friend_requests, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"friend_requests\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, friendRequestPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(friendRequestType, friendRequestMapping, append(wl, friendRequestPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update friend_requests row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for friend_requests")
	}

	if !cached {
		friendRequestUpdateCacheMut.Lock()
		friendRequestUpdateCache[key] = cache
		friendRequestUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q friendRequestQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for friend_requests")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for friend_requests")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o FriendRequestSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), friendRequestPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"friend_requests\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, friendRequestPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in friendRequest slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all friendRequest")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *FriendRequest) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no friend_requests provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(friendRequestColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	friendRequestUpsertCacheMut.RLock()
	cache, cached := friendRequestUpsertCache[key]
	friendRequestUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			friendRequestAllColumns,
			friendRequestColumnsWithDefault,
			friendRequestColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			friendRequestAllColumns,
			friendRequestPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert friend_requests, could not build update column list")
		}

		ret := strmangle.SetComplement(friendRequestAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(friendRequestPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert friend_requests, could not build conflict column list")
			}

			conflict = make([]string, len(friendRequestPrimaryKeyColumns))
			copy(conflict, friendRequestPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"friend_requests\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(friendRequestType, friendRequestMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(friendRequestType, friendRequestMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert friend_requests")
	}

	if !cached {
		friendRequestUpsertCacheMut.Lock()
		friendRequestUpsertCache[key] = cache
		friendRequestUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single FriendRequest record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *FriendRequest) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no FriendRequest provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), friendRequestPrimaryKeyMapping)
	sql := "DELETE FROM \"friend_requests\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from friend_requests")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for friend_requests")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q friendRequestQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no friendRequestQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from friend_requests")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for friend_requests")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o FriendRequestSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(friendRequestBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), friendRequestPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"friend_requests\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, friendRequestPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from friendRequest slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for friend_requests")
	}

	if len(friendRequestAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *FriendRequest) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindFriendRequest(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *FriendRequestSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := FriendRequestSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), friendRequestPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"friend_requests\".* FROM \"friend_requests\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, friendRequestPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in FriendRequestSlice")
	}

	*o = slice

	return nil
}

// FriendRequestExists checks if the FriendRequest row exists.
func FriendRequestExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"friend_requests\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if friend_requests exists")
	}

	return exists, nil
}

// Exists checks if the FriendRequest row exists.
func (o *FriendRequest) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return FriendRequestExists(ctx, exec, o.ID)
}
