// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// List is an object representing the database table.
type List struct {
	ID           string       `boil:"id" json:"id" toml:"id" yaml:"id"`
	Name         string       `boil:"name" json:"name" toml:"name" yaml:"name"`
	CreatedAt    time.Time    `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	OwnerID      string       `boil:"owner_id" json:"owner_id" toml:"owner_id" yaml:"owner_id"`
	SharingState SharingState `boil:"sharing_state" json:"sharing_state" toml:"sharing_state" yaml:"sharing_state"`

	R *listR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L listL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ListColumns = struct {
	ID           string
	Name         string
	CreatedAt    string
	OwnerID      string
	SharingState string
}{
	ID:           "id",
	Name:         "name",
	CreatedAt:    "created_at",
	OwnerID:      "owner_id",
	SharingState: "sharing_state",
}

var ListTableColumns = struct {
	ID           string
	Name         string
	CreatedAt    string
	OwnerID      string
	SharingState string
}{
	ID:           "lists.id",
	Name:         "lists.name",
	CreatedAt:    "lists.created_at",
	OwnerID:      "lists.owner_id",
	SharingState: "lists.sharing_state",
}

// Generated where

type whereHelperSharingState struct{ field string }

func (w whereHelperSharingState) EQ(x SharingState) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelperSharingState) NEQ(x SharingState) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelperSharingState) LT(x SharingState) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelperSharingState) LTE(x SharingState) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelperSharingState) GT(x SharingState) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelperSharingState) GTE(x SharingState) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}
func (w whereHelperSharingState) IN(slice []SharingState) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperSharingState) NIN(slice []SharingState) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

var ListWhere = struct {
	ID           whereHelperstring
	Name         whereHelperstring
	CreatedAt    whereHelpertime_Time
	OwnerID      whereHelperstring
	SharingState whereHelperSharingState
}{
	ID:           whereHelperstring{field: "\"lists\".\"id\""},
	Name:         whereHelperstring{field: "\"lists\".\"name\""},
	CreatedAt:    whereHelpertime_Time{field: "\"lists\".\"created_at\""},
	OwnerID:      whereHelperstring{field: "\"lists\".\"owner_id\""},
	SharingState: whereHelperSharingState{field: "\"lists\".\"sharing_state\""},
}

// ListRels is where relationship names are stored.
var ListRels = struct {
	Owner  string
	Things string
	Shares string
}{
	Owner:  "Owner",
	Things: "Things",
	Shares: "Shares",
}

// listR is where relationships are stored.
type listR struct {
	Owner  *User      `boil:"Owner" json:"Owner" toml:"Owner" yaml:"Owner"`
	Things ThingSlice `boil:"Things" json:"Things" toml:"Things" yaml:"Things"`
	Shares ShareSlice `boil:"Shares" json:"Shares" toml:"Shares" yaml:"Shares"`
}

// NewStruct creates a new relationship struct
func (*listR) NewStruct() *listR {
	return &listR{}
}

func (r *listR) GetOwner() *User {
	if r == nil {
		return nil
	}
	return r.Owner
}

func (r *listR) GetThings() ThingSlice {
	if r == nil {
		return nil
	}
	return r.Things
}

func (r *listR) GetShares() ShareSlice {
	if r == nil {
		return nil
	}
	return r.Shares
}

// listL is where Load methods for each relationship are stored.
type listL struct{}

var (
	listAllColumns            = []string{"id", "name", "created_at", "owner_id", "sharing_state"}
	listColumnsWithoutDefault = []string{"id", "name", "owner_id"}
	listColumnsWithDefault    = []string{"created_at", "sharing_state"}
	listPrimaryKeyColumns     = []string{"id"}
	listGeneratedColumns      = []string{}
)

type (
	// ListSlice is an alias for a slice of pointers to List.
	// This should almost always be used instead of []List.
	ListSlice []*List
	// ListHook is the signature for custom List hook methods
	ListHook func(context.Context, boil.ContextExecutor, *List) error

	listQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	listType                 = reflect.TypeOf(&List{})
	listMapping              = queries.MakeStructMapping(listType)
	listPrimaryKeyMapping, _ = queries.BindMapping(listType, listMapping, listPrimaryKeyColumns)
	listInsertCacheMut       sync.RWMutex
	listInsertCache          = make(map[string]insertCache)
	listUpdateCacheMut       sync.RWMutex
	listUpdateCache          = make(map[string]updateCache)
	listUpsertCacheMut       sync.RWMutex
	listUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var listAfterSelectMu sync.Mutex
var listAfterSelectHooks []ListHook

var listBeforeInsertMu sync.Mutex
var listBeforeInsertHooks []ListHook
var listAfterInsertMu sync.Mutex
var listAfterInsertHooks []ListHook

var listBeforeUpdateMu sync.Mutex
var listBeforeUpdateHooks []ListHook
var listAfterUpdateMu sync.Mutex
var listAfterUpdateHooks []ListHook

var listBeforeDeleteMu sync.Mutex
var listBeforeDeleteHooks []ListHook
var listAfterDeleteMu sync.Mutex
var listAfterDeleteHooks []ListHook

var listBeforeUpsertMu sync.Mutex
var listBeforeUpsertHooks []ListHook
var listAfterUpsertMu sync.Mutex
var listAfterUpsertHooks []ListHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *List) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range listAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *List) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range listBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *List) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range listAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *List) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range listBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *List) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range listAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *List) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range listBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *List) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range listAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *List) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range listBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *List) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range listAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddListHook registers your hook function for all future operations.
func AddListHook(hookPoint boil.HookPoint, listHook ListHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		listAfterSelectMu.Lock()
		listAfterSelectHooks = append(listAfterSelectHooks, listHook)
		listAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		listBeforeInsertMu.Lock()
		listBeforeInsertHooks = append(listBeforeInsertHooks, listHook)
		listBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		listAfterInsertMu.Lock()
		listAfterInsertHooks = append(listAfterInsertHooks, listHook)
		listAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		listBeforeUpdateMu.Lock()
		listBeforeUpdateHooks = append(listBeforeUpdateHooks, listHook)
		listBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		listAfterUpdateMu.Lock()
		listAfterUpdateHooks = append(listAfterUpdateHooks, listHook)
		listAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		listBeforeDeleteMu.Lock()
		listBeforeDeleteHooks = append(listBeforeDeleteHooks, listHook)
		listBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		listAfterDeleteMu.Lock()
		listAfterDeleteHooks = append(listAfterDeleteHooks, listHook)
		listAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		listBeforeUpsertMu.Lock()
		listBeforeUpsertHooks = append(listBeforeUpsertHooks, listHook)
		listBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		listAfterUpsertMu.Lock()
		listAfterUpsertHooks = append(listAfterUpsertHooks, listHook)
		listAfterUpsertMu.Unlock()
	}
}

// One returns a single list record from the query.
func (q listQuery) One(ctx context.Context, exec boil.ContextExecutor) (*List, error) {
	o := &List{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for lists")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all List records from the query.
func (q listQuery) All(ctx context.Context, exec boil.ContextExecutor) (ListSlice, error) {
	var o []*List

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to List slice")
	}

	if len(listAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all List records in the query.
func (q listQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count lists rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q listQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if lists exists")
	}

	return count > 0, nil
}

// Owner pointed to by the foreign key.
func (o *List) Owner(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.OwnerID),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// Things retrieves all the thing's Things with an executor.
func (o *List) Things(mods ...qm.QueryMod) thingQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.InnerJoin("\"lists_things\" on \"things\".\"id\" = \"lists_things\".\"thing_id\""),
		qm.Where("\"lists_things\".\"list_id\"=?", o.ID),
	)

	return Things(queryMods...)
}

// Shares retrieves all the share's Shares with an executor.
func (o *List) Shares(mods ...qm.QueryMod) shareQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.InnerJoin("\"shares_lists\" on \"shares\".\"id\" = \"shares_lists\".\"share_id\""),
		qm.Where("\"shares_lists\".\"list_id\"=?", o.ID),
	)

	return Shares(queryMods...)
}

// LoadOwner allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (listL) LoadOwner(ctx context.Context, e boil.ContextExecutor, singular bool, maybeList interface{}, mods queries.Applicator) error {
	var slice []*List
	var object *List

	if singular {
		var ok bool
		object, ok = maybeList.(*List)
		if !ok {
			object = new(List)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeList)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeList))
			}
		}
	} else {
		s, ok := maybeList.(*[]*List)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeList)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeList))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &listR{}
		}
		args[object.OwnerID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &listR{}
			}

			args[obj.OwnerID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(userAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Owner = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.OwnerLists = append(foreign.R.OwnerLists, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.OwnerID == foreign.ID {
				local.R.Owner = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.OwnerLists = append(foreign.R.OwnerLists, local)
				break
			}
		}
	}

	return nil
}

// LoadThings allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (listL) LoadThings(ctx context.Context, e boil.ContextExecutor, singular bool, maybeList interface{}, mods queries.Applicator) error {
	var slice []*List
	var object *List

	if singular {
		var ok bool
		object, ok = maybeList.(*List)
		if !ok {
			object = new(List)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeList)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeList))
			}
		}
	} else {
		s, ok := maybeList.(*[]*List)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeList)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeList))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &listR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &listR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.Select("\"things\".\"id\", \"things\".\"name\", \"things\".\"created_at\", \"things\".\"owner_id\", \"things\".\"description\", \"things\".\"private_note\", \"things\".\"quantity_unit\", \"things\".\"sharing_state\", \"a\".\"list_id\""),
		qm.From("\"things\""),
		qm.InnerJoin("\"lists_things\" as \"a\" on \"things\".\"id\" = \"a\".\"thing_id\""),
		qm.WhereIn("\"a\".\"list_id\" in ?", argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load things")
	}

	var resultSlice []*Thing

	var localJoinCols []string
	for results.Next() {
		one := new(Thing)
		var localJoinCol string

		err = results.Scan(&one.ID, &one.Name, &one.CreatedAt, &one.OwnerID, &one.Description, &one.PrivateNote, &one.QuantityUnit, &one.SharingState, &localJoinCol)
		if err != nil {
			return errors.Wrap(err, "failed to scan eager loaded results for things")
		}
		if err = results.Err(); err != nil {
			return errors.Wrap(err, "failed to plebian-bind eager loaded slice things")
		}

		resultSlice = append(resultSlice, one)
		localJoinCols = append(localJoinCols, localJoinCol)
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on things")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for things")
	}

	if len(thingAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.Things = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &thingR{}
			}
			foreign.R.Lists = append(foreign.R.Lists, object)
		}
		return nil
	}

	for i, foreign := range resultSlice {
		localJoinCol := localJoinCols[i]
		for _, local := range slice {
			if local.ID == localJoinCol {
				local.R.Things = append(local.R.Things, foreign)
				if foreign.R == nil {
					foreign.R = &thingR{}
				}
				foreign.R.Lists = append(foreign.R.Lists, local)
				break
			}
		}
	}

	return nil
}

// LoadShares allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (listL) LoadShares(ctx context.Context, e boil.ContextExecutor, singular bool, maybeList interface{}, mods queries.Applicator) error {
	var slice []*List
	var object *List

	if singular {
		var ok bool
		object, ok = maybeList.(*List)
		if !ok {
			object = new(List)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeList)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeList))
			}
		}
	} else {
		s, ok := maybeList.(*[]*List)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeList)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeList))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &listR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &listR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.Select("\"shares\".\"id\", \"shares\".\"created_at\", \"shares\".\"target_user_id\", \"shares\".\"owner_id\", \"a\".\"list_id\""),
		qm.From("\"shares\""),
		qm.InnerJoin("\"shares_lists\" as \"a\" on \"shares\".\"id\" = \"a\".\"share_id\""),
		qm.WhereIn("\"a\".\"list_id\" in ?", argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load shares")
	}

	var resultSlice []*Share

	var localJoinCols []string
	for results.Next() {
		one := new(Share)
		var localJoinCol string

		err = results.Scan(&one.ID, &one.CreatedAt, &one.TargetUserID, &one.OwnerID, &localJoinCol)
		if err != nil {
			return errors.Wrap(err, "failed to scan eager loaded results for shares")
		}
		if err = results.Err(); err != nil {
			return errors.Wrap(err, "failed to plebian-bind eager loaded slice shares")
		}

		resultSlice = append(resultSlice, one)
		localJoinCols = append(localJoinCols, localJoinCol)
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on shares")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for shares")
	}

	if len(shareAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.Shares = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &shareR{}
			}
			foreign.R.Lists = append(foreign.R.Lists, object)
		}
		return nil
	}

	for i, foreign := range resultSlice {
		localJoinCol := localJoinCols[i]
		for _, local := range slice {
			if local.ID == localJoinCol {
				local.R.Shares = append(local.R.Shares, foreign)
				if foreign.R == nil {
					foreign.R = &shareR{}
				}
				foreign.R.Lists = append(foreign.R.Lists, local)
				break
			}
		}
	}

	return nil
}

// SetOwner of the list to the related item.
// Sets o.R.Owner to related.
// Adds o to related.R.OwnerLists.
func (o *List) SetOwner(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"lists\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"owner_id"}),
		strmangle.WhereClause("\"", "\"", 2, listPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.OwnerID = related.ID
	if o.R == nil {
		o.R = &listR{
			Owner: related,
		}
	} else {
		o.R.Owner = related
	}

	if related.R == nil {
		related.R = &userR{
			OwnerLists: ListSlice{o},
		}
	} else {
		related.R.OwnerLists = append(related.R.OwnerLists, o)
	}

	return nil
}

// AddThings adds the given related objects to the existing relationships
// of the list, optionally inserting them as new records.
// Appends related to o.R.Things.
// Sets related.R.Lists appropriately.
func (o *List) AddThings(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Thing) error {
	var err error
	for _, rel := range related {
		if insert {
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		}
	}

	for _, rel := range related {
		query := "insert into \"lists_things\" (\"list_id\", \"thing_id\") values ($1, $2)"
		values := []interface{}{o.ID, rel.ID}

		if boil.IsDebug(ctx) {
			writer := boil.DebugWriterFrom(ctx)
			fmt.Fprintln(writer, query)
			fmt.Fprintln(writer, values)
		}
		_, err = exec.ExecContext(ctx, query, values...)
		if err != nil {
			return errors.Wrap(err, "failed to insert into join table")
		}
	}
	if o.R == nil {
		o.R = &listR{
			Things: related,
		}
	} else {
		o.R.Things = append(o.R.Things, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &thingR{
				Lists: ListSlice{o},
			}
		} else {
			rel.R.Lists = append(rel.R.Lists, o)
		}
	}
	return nil
}

// SetThings removes all previously related items of the
// list replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.Lists's Things accordingly.
// Replaces o.R.Things with related.
// Sets related.R.Lists's Things accordingly.
func (o *List) SetThings(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Thing) error {
	query := "delete from \"lists_things\" where \"list_id\" = $1"
	values := []interface{}{o.ID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	removeThingsFromListsSlice(o, related)
	if o.R != nil {
		o.R.Things = nil
	}

	return o.AddThings(ctx, exec, insert, related...)
}

// RemoveThings relationships from objects passed in.
// Removes related items from R.Things (uses pointer comparison, removal does not keep order)
// Sets related.R.Lists.
func (o *List) RemoveThings(ctx context.Context, exec boil.ContextExecutor, related ...*Thing) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	query := fmt.Sprintf(
		"delete from \"lists_things\" where \"list_id\" = $1 and \"thing_id\" in (%s)",
		strmangle.Placeholders(dialect.UseIndexPlaceholders, len(related), 2, 1),
	)
	values := []interface{}{o.ID}
	for _, rel := range related {
		values = append(values, rel.ID)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err = exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}
	removeThingsFromListsSlice(o, related)
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.Things {
			if rel != ri {
				continue
			}

			ln := len(o.R.Things)
			if ln > 1 && i < ln-1 {
				o.R.Things[i] = o.R.Things[ln-1]
			}
			o.R.Things = o.R.Things[:ln-1]
			break
		}
	}

	return nil
}

func removeThingsFromListsSlice(o *List, related []*Thing) {
	for _, rel := range related {
		if rel.R == nil {
			continue
		}
		for i, ri := range rel.R.Lists {
			if o.ID != ri.ID {
				continue
			}

			ln := len(rel.R.Lists)
			if ln > 1 && i < ln-1 {
				rel.R.Lists[i] = rel.R.Lists[ln-1]
			}
			rel.R.Lists = rel.R.Lists[:ln-1]
			break
		}
	}
}

// AddShares adds the given related objects to the existing relationships
// of the list, optionally inserting them as new records.
// Appends related to o.R.Shares.
// Sets related.R.Lists appropriately.
func (o *List) AddShares(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Share) error {
	var err error
	for _, rel := range related {
		if insert {
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		}
	}

	for _, rel := range related {
		query := "insert into \"shares_lists\" (\"list_id\", \"share_id\") values ($1, $2)"
		values := []interface{}{o.ID, rel.ID}

		if boil.IsDebug(ctx) {
			writer := boil.DebugWriterFrom(ctx)
			fmt.Fprintln(writer, query)
			fmt.Fprintln(writer, values)
		}
		_, err = exec.ExecContext(ctx, query, values...)
		if err != nil {
			return errors.Wrap(err, "failed to insert into join table")
		}
	}
	if o.R == nil {
		o.R = &listR{
			Shares: related,
		}
	} else {
		o.R.Shares = append(o.R.Shares, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &shareR{
				Lists: ListSlice{o},
			}
		} else {
			rel.R.Lists = append(rel.R.Lists, o)
		}
	}
	return nil
}

// SetShares removes all previously related items of the
// list replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.Lists's Shares accordingly.
// Replaces o.R.Shares with related.
// Sets related.R.Lists's Shares accordingly.
func (o *List) SetShares(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Share) error {
	query := "delete from \"shares_lists\" where \"list_id\" = $1"
	values := []interface{}{o.ID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	removeSharesFromListsSlice(o, related)
	if o.R != nil {
		o.R.Shares = nil
	}

	return o.AddShares(ctx, exec, insert, related...)
}

// RemoveShares relationships from objects passed in.
// Removes related items from R.Shares (uses pointer comparison, removal does not keep order)
// Sets related.R.Lists.
func (o *List) RemoveShares(ctx context.Context, exec boil.ContextExecutor, related ...*Share) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	query := fmt.Sprintf(
		"delete from \"shares_lists\" where \"list_id\" = $1 and \"share_id\" in (%s)",
		strmangle.Placeholders(dialect.UseIndexPlaceholders, len(related), 2, 1),
	)
	values := []interface{}{o.ID}
	for _, rel := range related {
		values = append(values, rel.ID)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err = exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}
	removeSharesFromListsSlice(o, related)
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.Shares {
			if rel != ri {
				continue
			}

			ln := len(o.R.Shares)
			if ln > 1 && i < ln-1 {
				o.R.Shares[i] = o.R.Shares[ln-1]
			}
			o.R.Shares = o.R.Shares[:ln-1]
			break
		}
	}

	return nil
}

func removeSharesFromListsSlice(o *List, related []*Share) {
	for _, rel := range related {
		if rel.R == nil {
			continue
		}
		for i, ri := range rel.R.Lists {
			if o.ID != ri.ID {
				continue
			}

			ln := len(rel.R.Lists)
			if ln > 1 && i < ln-1 {
				rel.R.Lists[i] = rel.R.Lists[ln-1]
			}
			rel.R.Lists = rel.R.Lists[:ln-1]
			break
		}
	}
}

// Lists retrieves all the records using an executor.
func Lists(mods ...qm.QueryMod) listQuery {
	mods = append(mods, qm.From("\"lists\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"lists\".*"})
	}

	return listQuery{q}
}

// FindList retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindList(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*List, error) {
	listObj := &List{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"lists\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, listObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from lists")
	}

	if err = listObj.doAfterSelectHooks(ctx, exec); err != nil {
		return listObj, err
	}

	return listObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *List) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no lists provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(listColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	listInsertCacheMut.RLock()
	cache, cached := listInsertCache[key]
	listInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			listAllColumns,
			listColumnsWithDefault,
			listColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(listType, listMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(listType, listMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"lists\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"lists\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into lists")
	}

	if !cached {
		listInsertCacheMut.Lock()
		listInsertCache[key] = cache
		listInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the List.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *List) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	listUpdateCacheMut.RLock()
	cache, cached := listUpdateCache[key]
	listUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			listAllColumns,
			listPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update lists, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"lists\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, listPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(listType, listMapping, append(wl, listPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update lists row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for lists")
	}

	if !cached {
		listUpdateCacheMut.Lock()
		listUpdateCache[key] = cache
		listUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q listQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for lists")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for lists")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ListSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), listPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"lists\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, listPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in list slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all list")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *List) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no lists provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(listColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	listUpsertCacheMut.RLock()
	cache, cached := listUpsertCache[key]
	listUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			listAllColumns,
			listColumnsWithDefault,
			listColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			listAllColumns,
			listPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert lists, could not build update column list")
		}

		ret := strmangle.SetComplement(listAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(listPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert lists, could not build conflict column list")
			}

			conflict = make([]string, len(listPrimaryKeyColumns))
			copy(conflict, listPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"lists\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(listType, listMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(listType, listMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert lists")
	}

	if !cached {
		listUpsertCacheMut.Lock()
		listUpsertCache[key] = cache
		listUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single List record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *List) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no List provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), listPrimaryKeyMapping)
	sql := "DELETE FROM \"lists\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from lists")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for lists")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q listQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no listQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from lists")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for lists")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ListSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(listBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), listPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"lists\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, listPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from list slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for lists")
	}

	if len(listAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *List) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindList(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ListSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ListSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), listPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"lists\".* FROM \"lists\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, listPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in ListSlice")
	}

	*o = slice

	return nil
}

// ListExists checks if the List row exists.
func ListExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"lists\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if lists exists")
	}

	return exists, nil
}

// Exists checks if the List row exists.
func (o *List) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return ListExists(ctx, exec, o.ID)
}
