// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// Property is an object representing the database table.
type Property struct {
	ID            string       `boil:"id" json:"id" toml:"id" yaml:"id"`
	Type          PropertyType `boil:"type" json:"type" toml:"type" yaml:"type"`
	Name          string       `boil:"name" json:"name" toml:"name" yaml:"name"`
	ValueString   null.String  `boil:"value_string" json:"value_string,omitempty" toml:"value_string" yaml:"value_string,omitempty"`
	ValueDatetime null.Time    `boil:"value_datetime" json:"value_datetime,omitempty" toml:"value_datetime" yaml:"value_datetime,omitempty"`
	ValueFloat    null.Float64 `boil:"value_float" json:"value_float,omitempty" toml:"value_float" yaml:"value_float,omitempty"`
	Unit          null.String  `boil:"unit" json:"unit,omitempty" toml:"unit" yaml:"unit,omitempty"`
	CreatedAt     time.Time    `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	ThingID       string       `boil:"thing_id" json:"thing_id" toml:"thing_id" yaml:"thing_id"`

	R *propertyR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L propertyL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var PropertyColumns = struct {
	ID            string
	Type          string
	Name          string
	ValueString   string
	ValueDatetime string
	ValueFloat    string
	Unit          string
	CreatedAt     string
	ThingID       string
}{
	ID:            "id",
	Type:          "type",
	Name:          "name",
	ValueString:   "value_string",
	ValueDatetime: "value_datetime",
	ValueFloat:    "value_float",
	Unit:          "unit",
	CreatedAt:     "created_at",
	ThingID:       "thing_id",
}

var PropertyTableColumns = struct {
	ID            string
	Type          string
	Name          string
	ValueString   string
	ValueDatetime string
	ValueFloat    string
	Unit          string
	CreatedAt     string
	ThingID       string
}{
	ID:            "properties.id",
	Type:          "properties.type",
	Name:          "properties.name",
	ValueString:   "properties.value_string",
	ValueDatetime: "properties.value_datetime",
	ValueFloat:    "properties.value_float",
	Unit:          "properties.unit",
	CreatedAt:     "properties.created_at",
	ThingID:       "properties.thing_id",
}

// Generated where

type whereHelperPropertyType struct{ field string }

func (w whereHelperPropertyType) EQ(x PropertyType) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelperPropertyType) NEQ(x PropertyType) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelperPropertyType) LT(x PropertyType) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelperPropertyType) LTE(x PropertyType) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelperPropertyType) GT(x PropertyType) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelperPropertyType) GTE(x PropertyType) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}
func (w whereHelperPropertyType) IN(slice []PropertyType) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperPropertyType) NIN(slice []PropertyType) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelpernull_Float64 struct{ field string }

func (w whereHelpernull_Float64) EQ(x null.Float64) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_Float64) NEQ(x null.Float64) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_Float64) LT(x null.Float64) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_Float64) LTE(x null.Float64) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_Float64) GT(x null.Float64) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_Float64) GTE(x null.Float64) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}
func (w whereHelpernull_Float64) IN(slice []float64) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelpernull_Float64) NIN(slice []float64) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

func (w whereHelpernull_Float64) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_Float64) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

var PropertyWhere = struct {
	ID            whereHelperstring
	Type          whereHelperPropertyType
	Name          whereHelperstring
	ValueString   whereHelpernull_String
	ValueDatetime whereHelpernull_Time
	ValueFloat    whereHelpernull_Float64
	Unit          whereHelpernull_String
	CreatedAt     whereHelpertime_Time
	ThingID       whereHelperstring
}{
	ID:            whereHelperstring{field: "\"properties\".\"id\""},
	Type:          whereHelperPropertyType{field: "\"properties\".\"type\""},
	Name:          whereHelperstring{field: "\"properties\".\"name\""},
	ValueString:   whereHelpernull_String{field: "\"properties\".\"value_string\""},
	ValueDatetime: whereHelpernull_Time{field: "\"properties\".\"value_datetime\""},
	ValueFloat:    whereHelpernull_Float64{field: "\"properties\".\"value_float\""},
	Unit:          whereHelpernull_String{field: "\"properties\".\"unit\""},
	CreatedAt:     whereHelpertime_Time{field: "\"properties\".\"created_at\""},
	ThingID:       whereHelperstring{field: "\"properties\".\"thing_id\""},
}

// PropertyRels is where relationship names are stored.
var PropertyRels = struct {
	Thing string
}{
	Thing: "Thing",
}

// propertyR is where relationships are stored.
type propertyR struct {
	Thing *Thing `boil:"Thing" json:"Thing" toml:"Thing" yaml:"Thing"`
}

// NewStruct creates a new relationship struct
func (*propertyR) NewStruct() *propertyR {
	return &propertyR{}
}

func (o *Property) GetThing() *Thing {
	if o == nil {
		return nil
	}

	return o.R.GetThing()
}

func (r *propertyR) GetThing() *Thing {
	if r == nil {
		return nil
	}

	return r.Thing
}

// propertyL is where Load methods for each relationship are stored.
type propertyL struct{}

var (
	propertyAllColumns            = []string{"id", "type", "name", "value_string", "value_datetime", "value_float", "unit", "created_at", "thing_id"}
	propertyColumnsWithoutDefault = []string{"id", "type", "name", "thing_id"}
	propertyColumnsWithDefault    = []string{"value_string", "value_datetime", "value_float", "unit", "created_at"}
	propertyPrimaryKeyColumns     = []string{"id"}
	propertyGeneratedColumns      = []string{}
)

type (
	// PropertySlice is an alias for a slice of pointers to Property.
	// This should almost always be used instead of []Property.
	PropertySlice []*Property
	// PropertyHook is the signature for custom Property hook methods
	PropertyHook func(context.Context, boil.ContextExecutor, *Property) error

	propertyQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	propertyType                 = reflect.TypeOf(&Property{})
	propertyMapping              = queries.MakeStructMapping(propertyType)
	propertyPrimaryKeyMapping, _ = queries.BindMapping(propertyType, propertyMapping, propertyPrimaryKeyColumns)
	propertyInsertCacheMut       sync.RWMutex
	propertyInsertCache          = make(map[string]insertCache)
	propertyUpdateCacheMut       sync.RWMutex
	propertyUpdateCache          = make(map[string]updateCache)
	propertyUpsertCacheMut       sync.RWMutex
	propertyUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var propertyAfterSelectMu sync.Mutex
var propertyAfterSelectHooks []PropertyHook

var propertyBeforeInsertMu sync.Mutex
var propertyBeforeInsertHooks []PropertyHook
var propertyAfterInsertMu sync.Mutex
var propertyAfterInsertHooks []PropertyHook

var propertyBeforeUpdateMu sync.Mutex
var propertyBeforeUpdateHooks []PropertyHook
var propertyAfterUpdateMu sync.Mutex
var propertyAfterUpdateHooks []PropertyHook

var propertyBeforeDeleteMu sync.Mutex
var propertyBeforeDeleteHooks []PropertyHook
var propertyAfterDeleteMu sync.Mutex
var propertyAfterDeleteHooks []PropertyHook

var propertyBeforeUpsertMu sync.Mutex
var propertyBeforeUpsertHooks []PropertyHook
var propertyAfterUpsertMu sync.Mutex
var propertyAfterUpsertHooks []PropertyHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Property) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range propertyAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Property) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range propertyBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Property) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range propertyAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Property) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range propertyBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Property) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range propertyAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Property) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range propertyBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Property) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range propertyAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Property) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range propertyBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Property) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range propertyAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddPropertyHook registers your hook function for all future operations.
func AddPropertyHook(hookPoint boil.HookPoint, propertyHook PropertyHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		propertyAfterSelectMu.Lock()
		propertyAfterSelectHooks = append(propertyAfterSelectHooks, propertyHook)
		propertyAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		propertyBeforeInsertMu.Lock()
		propertyBeforeInsertHooks = append(propertyBeforeInsertHooks, propertyHook)
		propertyBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		propertyAfterInsertMu.Lock()
		propertyAfterInsertHooks = append(propertyAfterInsertHooks, propertyHook)
		propertyAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		propertyBeforeUpdateMu.Lock()
		propertyBeforeUpdateHooks = append(propertyBeforeUpdateHooks, propertyHook)
		propertyBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		propertyAfterUpdateMu.Lock()
		propertyAfterUpdateHooks = append(propertyAfterUpdateHooks, propertyHook)
		propertyAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		propertyBeforeDeleteMu.Lock()
		propertyBeforeDeleteHooks = append(propertyBeforeDeleteHooks, propertyHook)
		propertyBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		propertyAfterDeleteMu.Lock()
		propertyAfterDeleteHooks = append(propertyAfterDeleteHooks, propertyHook)
		propertyAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		propertyBeforeUpsertMu.Lock()
		propertyBeforeUpsertHooks = append(propertyBeforeUpsertHooks, propertyHook)
		propertyBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		propertyAfterUpsertMu.Lock()
		propertyAfterUpsertHooks = append(propertyAfterUpsertHooks, propertyHook)
		propertyAfterUpsertMu.Unlock()
	}
}

// One returns a single property record from the query.
func (q propertyQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Property, error) {
	o := &Property{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for properties")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all Property records from the query.
func (q propertyQuery) All(ctx context.Context, exec boil.ContextExecutor) (PropertySlice, error) {
	var o []*Property

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Property slice")
	}

	if len(propertyAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all Property records in the query.
func (q propertyQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count properties rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q propertyQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if properties exists")
	}

	return count > 0, nil
}

// Thing pointed to by the foreign key.
func (o *Property) Thing(mods ...qm.QueryMod) thingQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.ThingID),
	}

	queryMods = append(queryMods, mods...)

	return Things(queryMods...)
}

// LoadThing allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (propertyL) LoadThing(ctx context.Context, e boil.ContextExecutor, singular bool, maybeProperty interface{}, mods queries.Applicator) error {
	var slice []*Property
	var object *Property

	if singular {
		var ok bool
		object, ok = maybeProperty.(*Property)
		if !ok {
			object = new(Property)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeProperty)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeProperty))
			}
		}
	} else {
		s, ok := maybeProperty.(*[]*Property)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeProperty)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeProperty))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &propertyR{}
		}
		args[object.ThingID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &propertyR{}
			}

			args[obj.ThingID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`things`),
		qm.WhereIn(`things.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Thing")
	}

	var resultSlice []*Thing
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Thing")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for things")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for things")
	}

	if len(thingAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Thing = foreign
		if foreign.R == nil {
			foreign.R = &thingR{}
		}
		foreign.R.Properties = append(foreign.R.Properties, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.ThingID == foreign.ID {
				local.R.Thing = foreign
				if foreign.R == nil {
					foreign.R = &thingR{}
				}
				foreign.R.Properties = append(foreign.R.Properties, local)
				break
			}
		}
	}

	return nil
}

// SetThing of the property to the related item.
// Sets o.R.Thing to related.
// Adds o to related.R.Properties.
func (o *Property) SetThing(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Thing) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"properties\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"thing_id"}),
		strmangle.WhereClause("\"", "\"", 2, propertyPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.ThingID = related.ID
	if o.R == nil {
		o.R = &propertyR{
			Thing: related,
		}
	} else {
		o.R.Thing = related
	}

	if related.R == nil {
		related.R = &thingR{
			Properties: PropertySlice{o},
		}
	} else {
		related.R.Properties = append(related.R.Properties, o)
	}

	return nil
}

// Properties retrieves all the records using an executor.
func Properties(mods ...qm.QueryMod) propertyQuery {
	mods = append(mods, qm.From("\"properties\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"properties\".*"})
	}

	return propertyQuery{q}
}

// FindProperty retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindProperty(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*Property, error) {
	propertyObj := &Property{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"properties\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, propertyObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from properties")
	}

	if err = propertyObj.doAfterSelectHooks(ctx, exec); err != nil {
		return propertyObj, err
	}

	return propertyObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Property) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no properties provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(propertyColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	propertyInsertCacheMut.RLock()
	cache, cached := propertyInsertCache[key]
	propertyInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			propertyAllColumns,
			propertyColumnsWithDefault,
			propertyColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(propertyType, propertyMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(propertyType, propertyMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"properties\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"properties\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into properties")
	}

	if !cached {
		propertyInsertCacheMut.Lock()
		propertyInsertCache[key] = cache
		propertyInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the Property.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Property) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	propertyUpdateCacheMut.RLock()
	cache, cached := propertyUpdateCache[key]
	propertyUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			propertyAllColumns,
			propertyPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update properties, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"properties\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, propertyPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(propertyType, propertyMapping, append(wl, propertyPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update properties row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for properties")
	}

	if !cached {
		propertyUpdateCacheMut.Lock()
		propertyUpdateCache[key] = cache
		propertyUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q propertyQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for properties")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for properties")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o PropertySlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), propertyPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"properties\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, propertyPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in property slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all property")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Property) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no properties provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(propertyColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	propertyUpsertCacheMut.RLock()
	cache, cached := propertyUpsertCache[key]
	propertyUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			propertyAllColumns,
			propertyColumnsWithDefault,
			propertyColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			propertyAllColumns,
			propertyPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert properties, could not build update column list")
		}

		ret := strmangle.SetComplement(propertyAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(propertyPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert properties, could not build conflict column list")
			}

			conflict = make([]string, len(propertyPrimaryKeyColumns))
			copy(conflict, propertyPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"properties\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(propertyType, propertyMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(propertyType, propertyMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert properties")
	}

	if !cached {
		propertyUpsertCacheMut.Lock()
		propertyUpsertCache[key] = cache
		propertyUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single Property record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Property) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no Property provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), propertyPrimaryKeyMapping)
	sql := "DELETE FROM \"properties\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from properties")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for properties")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q propertyQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no propertyQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from properties")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for properties")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o PropertySlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(propertyBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), propertyPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"properties\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, propertyPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from property slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for properties")
	}

	if len(propertyAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Property) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindProperty(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *PropertySlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := PropertySlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), propertyPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"properties\".* FROM \"properties\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, propertyPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in PropertySlice")
	}

	*o = slice

	return nil
}

// PropertyExists checks if the Property row exists.
func PropertyExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"properties\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if properties exists")
	}

	return exists, nil
}

// Exists checks if the Property row exists.
func (o *Property) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return PropertyExists(ctx, exec, o.ID)
}
