// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// PublicShare is an object representing the database table.
type PublicShare struct {
	ID        string      `boil:"id" json:"id" toml:"id" yaml:"id"`
	CreatedAt time.Time   `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	OwnerID   string      `boil:"owner_id" json:"owner_id" toml:"owner_id" yaml:"owner_id"`
	ThingID   null.String `boil:"thing_id" json:"thing_id,omitempty" toml:"thing_id" yaml:"thing_id,omitempty"`
	ListID    null.String `boil:"list_id" json:"list_id,omitempty" toml:"list_id" yaml:"list_id,omitempty"`

	R *publicShareR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L publicShareL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var PublicShareColumns = struct {
	ID        string
	CreatedAt string
	OwnerID   string
	ThingID   string
	ListID    string
}{
	ID:        "id",
	CreatedAt: "created_at",
	OwnerID:   "owner_id",
	ThingID:   "thing_id",
	ListID:    "list_id",
}

var PublicShareTableColumns = struct {
	ID        string
	CreatedAt string
	OwnerID   string
	ThingID   string
	ListID    string
}{
	ID:        "public_shares.id",
	CreatedAt: "public_shares.created_at",
	OwnerID:   "public_shares.owner_id",
	ThingID:   "public_shares.thing_id",
	ListID:    "public_shares.list_id",
}

// Generated where

var PublicShareWhere = struct {
	ID        whereHelperstring
	CreatedAt whereHelpertime_Time
	OwnerID   whereHelperstring
	ThingID   whereHelpernull_String
	ListID    whereHelpernull_String
}{
	ID:        whereHelperstring{field: "\"public_shares\".\"id\""},
	CreatedAt: whereHelpertime_Time{field: "\"public_shares\".\"created_at\""},
	OwnerID:   whereHelperstring{field: "\"public_shares\".\"owner_id\""},
	ThingID:   whereHelpernull_String{field: "\"public_shares\".\"thing_id\""},
	ListID:    whereHelpernull_String{field: "\"public_shares\".\"list_id\""},
}

// PublicShareRels is where relationship names are stored.
var PublicShareRels = struct {
	List  string
	Owner string
	Thing string
}{
	List:  "List",
	Owner: "Owner",
	Thing: "Thing",
}

// publicShareR is where relationships are stored.
type publicShareR struct {
	List  *List  `boil:"List" json:"List" toml:"List" yaml:"List"`
	Owner *User  `boil:"Owner" json:"Owner" toml:"Owner" yaml:"Owner"`
	Thing *Thing `boil:"Thing" json:"Thing" toml:"Thing" yaml:"Thing"`
}

// NewStruct creates a new relationship struct
func (*publicShareR) NewStruct() *publicShareR {
	return &publicShareR{}
}

func (o *PublicShare) GetList() *List {
	if o == nil {
		return nil
	}

	return o.R.GetList()
}

func (r *publicShareR) GetList() *List {
	if r == nil {
		return nil
	}

	return r.List
}

func (o *PublicShare) GetOwner() *User {
	if o == nil {
		return nil
	}

	return o.R.GetOwner()
}

func (r *publicShareR) GetOwner() *User {
	if r == nil {
		return nil
	}

	return r.Owner
}

func (o *PublicShare) GetThing() *Thing {
	if o == nil {
		return nil
	}

	return o.R.GetThing()
}

func (r *publicShareR) GetThing() *Thing {
	if r == nil {
		return nil
	}

	return r.Thing
}

// publicShareL is where Load methods for each relationship are stored.
type publicShareL struct{}

var (
	publicShareAllColumns            = []string{"id", "created_at", "owner_id", "thing_id", "list_id"}
	publicShareColumnsWithoutDefault = []string{"id", "owner_id"}
	publicShareColumnsWithDefault    = []string{"created_at", "thing_id", "list_id"}
	publicSharePrimaryKeyColumns     = []string{"id"}
	publicShareGeneratedColumns      = []string{}
)

type (
	// PublicShareSlice is an alias for a slice of pointers to PublicShare.
	// This should almost always be used instead of []PublicShare.
	PublicShareSlice []*PublicShare
	// PublicShareHook is the signature for custom PublicShare hook methods
	PublicShareHook func(context.Context, boil.ContextExecutor, *PublicShare) error

	publicShareQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	publicShareType                 = reflect.TypeOf(&PublicShare{})
	publicShareMapping              = queries.MakeStructMapping(publicShareType)
	publicSharePrimaryKeyMapping, _ = queries.BindMapping(publicShareType, publicShareMapping, publicSharePrimaryKeyColumns)
	publicShareInsertCacheMut       sync.RWMutex
	publicShareInsertCache          = make(map[string]insertCache)
	publicShareUpdateCacheMut       sync.RWMutex
	publicShareUpdateCache          = make(map[string]updateCache)
	publicShareUpsertCacheMut       sync.RWMutex
	publicShareUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var publicShareAfterSelectMu sync.Mutex
var publicShareAfterSelectHooks []PublicShareHook

var publicShareBeforeInsertMu sync.Mutex
var publicShareBeforeInsertHooks []PublicShareHook
var publicShareAfterInsertMu sync.Mutex
var publicShareAfterInsertHooks []PublicShareHook

var publicShareBeforeUpdateMu sync.Mutex
var publicShareBeforeUpdateHooks []PublicShareHook
var publicShareAfterUpdateMu sync.Mutex
var publicShareAfterUpdateHooks []PublicShareHook

var publicShareBeforeDeleteMu sync.Mutex
var publicShareBeforeDeleteHooks []PublicShareHook
var publicShareAfterDeleteMu sync.Mutex
var publicShareAfterDeleteHooks []PublicShareHook

var publicShareBeforeUpsertMu sync.Mutex
var publicShareBeforeUpsertHooks []PublicShareHook
var publicShareAfterUpsertMu sync.Mutex
var publicShareAfterUpsertHooks []PublicShareHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *PublicShare) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range publicShareAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *PublicShare) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range publicShareBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *PublicShare) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range publicShareAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *PublicShare) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range publicShareBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *PublicShare) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range publicShareAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *PublicShare) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range publicShareBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *PublicShare) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range publicShareAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *PublicShare) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range publicShareBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *PublicShare) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range publicShareAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddPublicShareHook registers your hook function for all future operations.
func AddPublicShareHook(hookPoint boil.HookPoint, publicShareHook PublicShareHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		publicShareAfterSelectMu.Lock()
		publicShareAfterSelectHooks = append(publicShareAfterSelectHooks, publicShareHook)
		publicShareAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		publicShareBeforeInsertMu.Lock()
		publicShareBeforeInsertHooks = append(publicShareBeforeInsertHooks, publicShareHook)
		publicShareBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		publicShareAfterInsertMu.Lock()
		publicShareAfterInsertHooks = append(publicShareAfterInsertHooks, publicShareHook)
		publicShareAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		publicShareBeforeUpdateMu.Lock()
		publicShareBeforeUpdateHooks = append(publicShareBeforeUpdateHooks, publicShareHook)
		publicShareBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		publicShareAfterUpdateMu.Lock()
		publicShareAfterUpdateHooks = append(publicShareAfterUpdateHooks, publicShareHook)
		publicShareAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		publicShareBeforeDeleteMu.Lock()
		publicShareBeforeDeleteHooks = append(publicShareBeforeDeleteHooks, publicShareHook)
		publicShareBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		publicShareAfterDeleteMu.Lock()
		publicShareAfterDeleteHooks = append(publicShareAfterDeleteHooks, publicShareHook)
		publicShareAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		publicShareBeforeUpsertMu.Lock()
		publicShareBeforeUpsertHooks = append(publicShareBeforeUpsertHooks, publicShareHook)
		publicShareBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		publicShareAfterUpsertMu.Lock()
		publicShareAfterUpsertHooks = append(publicShareAfterUpsertHooks, publicShareHook)
		publicShareAfterUpsertMu.Unlock()
	}
}

// One returns a single publicShare record from the query.
func (q publicShareQuery) One(ctx context.Context, exec boil.ContextExecutor) (*PublicShare, error) {
	o := &PublicShare{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for public_shares")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all PublicShare records from the query.
func (q publicShareQuery) All(ctx context.Context, exec boil.ContextExecutor) (PublicShareSlice, error) {
	var o []*PublicShare

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to PublicShare slice")
	}

	if len(publicShareAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all PublicShare records in the query.
func (q publicShareQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count public_shares rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q publicShareQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if public_shares exists")
	}

	return count > 0, nil
}

// List pointed to by the foreign key.
func (o *PublicShare) List(mods ...qm.QueryMod) listQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.ListID),
	}

	queryMods = append(queryMods, mods...)

	return Lists(queryMods...)
}

// Owner pointed to by the foreign key.
func (o *PublicShare) Owner(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.OwnerID),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// Thing pointed to by the foreign key.
func (o *PublicShare) Thing(mods ...qm.QueryMod) thingQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.ThingID),
	}

	queryMods = append(queryMods, mods...)

	return Things(queryMods...)
}

// LoadList allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (publicShareL) LoadList(ctx context.Context, e boil.ContextExecutor, singular bool, maybePublicShare any, mods queries.Applicator) error {
	var slice []*PublicShare
	var object *PublicShare

	if singular {
		var ok bool
		object, ok = maybePublicShare.(*PublicShare)
		if !ok {
			object = new(PublicShare)
			ok = queries.SetFromEmbeddedStruct(&object, &maybePublicShare)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybePublicShare))
			}
		}
	} else {
		s, ok := maybePublicShare.(*[]*PublicShare)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybePublicShare)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybePublicShare))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &publicShareR{}
		}
		if !queries.IsNil(object.ListID) {
			args[object.ListID] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &publicShareR{}
			}

			if !queries.IsNil(obj.ListID) {
				args[obj.ListID] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`lists`),
		qm.WhereIn(`lists.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load List")
	}

	var resultSlice []*List
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice List")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for lists")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for lists")
	}

	if len(listAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.List = foreign
		if foreign.R == nil {
			foreign.R = &listR{}
		}
		foreign.R.PublicShares = append(foreign.R.PublicShares, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.ListID, foreign.ID) {
				local.R.List = foreign
				if foreign.R == nil {
					foreign.R = &listR{}
				}
				foreign.R.PublicShares = append(foreign.R.PublicShares, local)
				break
			}
		}
	}

	return nil
}

// LoadOwner allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (publicShareL) LoadOwner(ctx context.Context, e boil.ContextExecutor, singular bool, maybePublicShare any, mods queries.Applicator) error {
	var slice []*PublicShare
	var object *PublicShare

	if singular {
		var ok bool
		object, ok = maybePublicShare.(*PublicShare)
		if !ok {
			object = new(PublicShare)
			ok = queries.SetFromEmbeddedStruct(&object, &maybePublicShare)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybePublicShare))
			}
		}
	} else {
		s, ok := maybePublicShare.(*[]*PublicShare)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybePublicShare)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybePublicShare))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &publicShareR{}
		}
		args[object.OwnerID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &publicShareR{}
			}

			args[obj.OwnerID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(userAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Owner = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.OwnerPublicShares = append(foreign.R.OwnerPublicShares, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.OwnerID == foreign.ID {
				local.R.Owner = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.OwnerPublicShares = append(foreign.R.OwnerPublicShares, local)
				break
			}
		}
	}

	return nil
}

// LoadThing allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (publicShareL) LoadThing(ctx context.Context, e boil.ContextExecutor, singular bool, maybePublicShare any, mods queries.Applicator) error {
	var slice []*PublicShare
	var object *PublicShare

	if singular {
		var ok bool
		object, ok = maybePublicShare.(*PublicShare)
		if !ok {
			object = new(PublicShare)
			ok = queries.SetFromEmbeddedStruct(&object, &maybePublicShare)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybePublicShare))
			}
		}
	} else {
		s, ok := maybePublicShare.(*[]*PublicShare)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybePublicShare)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybePublicShare))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &publicShareR{}
		}
		if !queries.IsNil(object.ThingID) {
			args[object.ThingID] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &publicShareR{}
			}

			if !queries.IsNil(obj.ThingID) {
				args[obj.ThingID] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`things`),
		qm.WhereIn(`things.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Thing")
	}

	var resultSlice []*Thing
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Thing")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for things")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for things")
	}

	if len(thingAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Thing = foreign
		if foreign.R == nil {
			foreign.R = &thingR{}
		}
		foreign.R.PublicShares = append(foreign.R.PublicShares, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.ThingID, foreign.ID) {
				local.R.Thing = foreign
				if foreign.R == nil {
					foreign.R = &thingR{}
				}
				foreign.R.PublicShares = append(foreign.R.PublicShares, local)
				break
			}
		}
	}

	return nil
}

// SetList of the publicShare to the related item.
// Sets o.R.List to related.
// Adds o to related.R.PublicShares.
func (o *PublicShare) SetList(ctx context.Context, exec boil.ContextExecutor, insert bool, related *List) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"public_shares\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"list_id"}),
		strmangle.WhereClause("\"", "\"", 2, publicSharePrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.ListID, related.ID)
	if o.R == nil {
		o.R = &publicShareR{
			List: related,
		}
	} else {
		o.R.List = related
	}

	if related.R == nil {
		related.R = &listR{
			PublicShares: PublicShareSlice{o},
		}
	} else {
		related.R.PublicShares = append(related.R.PublicShares, o)
	}

	return nil
}

// RemoveList relationship.
// Sets o.R.List to nil.
// Removes o from all passed in related items' relationships struct.
func (o *PublicShare) RemoveList(ctx context.Context, exec boil.ContextExecutor, related *List) error {
	var err error

	queries.SetScanner(&o.ListID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("list_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.List = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.PublicShares {
		if queries.Equal(o.ListID, ri.ListID) {
			continue
		}

		ln := len(related.R.PublicShares)
		if ln > 1 && i < ln-1 {
			related.R.PublicShares[i] = related.R.PublicShares[ln-1]
		}
		related.R.PublicShares = related.R.PublicShares[:ln-1]
		break
	}
	return nil
}

// SetOwner of the publicShare to the related item.
// Sets o.R.Owner to related.
// Adds o to related.R.OwnerPublicShares.
func (o *PublicShare) SetOwner(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"public_shares\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"owner_id"}),
		strmangle.WhereClause("\"", "\"", 2, publicSharePrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.OwnerID = related.ID
	if o.R == nil {
		o.R = &publicShareR{
			Owner: related,
		}
	} else {
		o.R.Owner = related
	}

	if related.R == nil {
		related.R = &userR{
			OwnerPublicShares: PublicShareSlice{o},
		}
	} else {
		related.R.OwnerPublicShares = append(related.R.OwnerPublicShares, o)
	}

	return nil
}

// SetThing of the publicShare to the related item.
// Sets o.R.Thing to related.
// Adds o to related.R.PublicShares.
func (o *PublicShare) SetThing(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Thing) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"public_shares\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"thing_id"}),
		strmangle.WhereClause("\"", "\"", 2, publicSharePrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.ThingID, related.ID)
	if o.R == nil {
		o.R = &publicShareR{
			Thing: related,
		}
	} else {
		o.R.Thing = related
	}

	if related.R == nil {
		related.R = &thingR{
			PublicShares: PublicShareSlice{o},
		}
	} else {
		related.R.PublicShares = append(related.R.PublicShares, o)
	}

	return nil
}

// RemoveThing relationship.
// Sets o.R.Thing to nil.
// Removes o from all passed in related items' relationships struct.
func (o *PublicShare) RemoveThing(ctx context.Context, exec boil.ContextExecutor, related *Thing) error {
	var err error

	queries.SetScanner(&o.ThingID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("thing_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.Thing = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.PublicShares {
		if queries.Equal(o.ThingID, ri.ThingID) {
			continue
		}

		ln := len(related.R.PublicShares)
		if ln > 1 && i < ln-1 {
			related.R.PublicShares[i] = related.R.PublicShares[ln-1]
		}
		related.R.PublicShares = related.R.PublicShares[:ln-1]
		break
	}
	return nil
}

// PublicShares retrieves all the records using an executor.
func PublicShares(mods ...qm.QueryMod) publicShareQuery {
	mods = append(mods, qm.From("\"public_shares\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"public_shares\".*"})
	}

	return publicShareQuery{q}
}

// FindPublicShare retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindPublicShare(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*PublicShare, error) {
	publicShareObj := &PublicShare{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"public_shares\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, publicShareObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from public_shares")
	}

	if err = publicShareObj.doAfterSelectHooks(ctx, exec); err != nil {
		return publicShareObj, err
	}

	return publicShareObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *PublicShare) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no public_shares provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(publicShareColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	publicShareInsertCacheMut.RLock()
	cache, cached := publicShareInsertCache[key]
	publicShareInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			publicShareAllColumns,
			publicShareColumnsWithDefault,
			publicShareColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(publicShareType, publicShareMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(publicShareType, publicShareMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"public_shares\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"public_shares\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into public_shares")
	}

	if !cached {
		publicShareInsertCacheMut.Lock()
		publicShareInsertCache[key] = cache
		publicShareInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the PublicShare.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *PublicShare) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	publicShareUpdateCacheMut.RLock()
	cache, cached := publicShareUpdateCache[key]
	publicShareUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			publicShareAllColumns,
			publicSharePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update public_shares, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"public_shares\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, publicSharePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(publicShareType, publicShareMapping, append(wl, publicSharePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update public_shares row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for public_shares")
	}

	if !cached {
		publicShareUpdateCacheMut.Lock()
		publicShareUpdateCache[key] = cache
		publicShareUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q publicShareQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for public_shares")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for public_shares")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o PublicShareSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), publicSharePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"public_shares\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, publicSharePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in publicShare slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all publicShare")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *PublicShare) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no public_shares provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(publicShareColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	publicShareUpsertCacheMut.RLock()
	cache, cached := publicShareUpsertCache[key]
	publicShareUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			publicShareAllColumns,
			publicShareColumnsWithDefault,
			publicShareColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			publicShareAllColumns,
			publicSharePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert public_shares, could not build update column list")
		}

		ret := strmangle.SetComplement(publicShareAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(publicSharePrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert public_shares, could not build conflict column list")
			}

			conflict = make([]string, len(publicSharePrimaryKeyColumns))
			copy(conflict, publicSharePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"public_shares\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(publicShareType, publicShareMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(publicShareType, publicShareMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert public_shares")
	}

	if !cached {
		publicShareUpsertCacheMut.Lock()
		publicShareUpsertCache[key] = cache
		publicShareUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single PublicShare record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *PublicShare) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no PublicShare provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), publicSharePrimaryKeyMapping)
	sql := "DELETE FROM \"public_shares\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from public_shares")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for public_shares")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q publicShareQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no publicShareQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from public_shares")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for public_shares")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o PublicShareSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(publicShareBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), publicSharePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"public_shares\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, publicSharePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from publicShare slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for public_shares")
	}

	if len(publicShareAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *PublicShare) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindPublicShare(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *PublicShareSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := PublicShareSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), publicSharePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"public_shares\".* FROM \"public_shares\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, publicSharePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in PublicShareSlice")
	}

	*o = slice

	return nil
}

// PublicShareExists checks if the PublicShare row exists.
func PublicShareExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"public_shares\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if public_shares exists")
	}

	return exists, nil
}

// Exists checks if the PublicShare row exists.
func (o *PublicShare) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return PublicShareExists(ctx, exec, o.ID)
}
