// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// QuantityEntry is an object representing the database table.
type QuantityEntry struct {
	ID         string    `boil:"id" json:"id" toml:"id" yaml:"id"`
	ThingID    string    `boil:"thing_id" json:"thing_id" toml:"thing_id" yaml:"thing_id"`
	DeltaValue int64     `boil:"delta_value" json:"delta_value" toml:"delta_value" yaml:"delta_value"`
	CreatedAt  time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`

	R *quantityEntryR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L quantityEntryL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var QuantityEntryColumns = struct {
	ID         string
	ThingID    string
	DeltaValue string
	CreatedAt  string
}{
	ID:         "id",
	ThingID:    "thing_id",
	DeltaValue: "delta_value",
	CreatedAt:  "created_at",
}

var QuantityEntryTableColumns = struct {
	ID         string
	ThingID    string
	DeltaValue string
	CreatedAt  string
}{
	ID:         "quantity_entries.id",
	ThingID:    "quantity_entries.thing_id",
	DeltaValue: "quantity_entries.delta_value",
	CreatedAt:  "quantity_entries.created_at",
}

// Generated where

type whereHelperint64 struct{ field string }

func (w whereHelperint64) EQ(x int64) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperint64) NEQ(x int64) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperint64) LT(x int64) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperint64) LTE(x int64) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperint64) GT(x int64) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperint64) GTE(x int64) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperint64) IN(slice []int64) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperint64) NIN(slice []int64) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

var QuantityEntryWhere = struct {
	ID         whereHelperstring
	ThingID    whereHelperstring
	DeltaValue whereHelperint64
	CreatedAt  whereHelpertime_Time
}{
	ID:         whereHelperstring{field: "\"quantity_entries\".\"id\""},
	ThingID:    whereHelperstring{field: "\"quantity_entries\".\"thing_id\""},
	DeltaValue: whereHelperint64{field: "\"quantity_entries\".\"delta_value\""},
	CreatedAt:  whereHelpertime_Time{field: "\"quantity_entries\".\"created_at\""},
}

// QuantityEntryRels is where relationship names are stored.
var QuantityEntryRels = struct {
	Thing string
}{
	Thing: "Thing",
}

// quantityEntryR is where relationships are stored.
type quantityEntryR struct {
	Thing *Thing `boil:"Thing" json:"Thing" toml:"Thing" yaml:"Thing"`
}

// NewStruct creates a new relationship struct
func (*quantityEntryR) NewStruct() *quantityEntryR {
	return &quantityEntryR{}
}

func (r *quantityEntryR) GetThing() *Thing {
	if r == nil {
		return nil
	}
	return r.Thing
}

// quantityEntryL is where Load methods for each relationship are stored.
type quantityEntryL struct{}

var (
	quantityEntryAllColumns            = []string{"id", "thing_id", "delta_value", "created_at"}
	quantityEntryColumnsWithoutDefault = []string{"id", "thing_id", "delta_value"}
	quantityEntryColumnsWithDefault    = []string{"created_at"}
	quantityEntryPrimaryKeyColumns     = []string{"id"}
	quantityEntryGeneratedColumns      = []string{}
)

type (
	// QuantityEntrySlice is an alias for a slice of pointers to QuantityEntry.
	// This should almost always be used instead of []QuantityEntry.
	QuantityEntrySlice []*QuantityEntry
	// QuantityEntryHook is the signature for custom QuantityEntry hook methods
	QuantityEntryHook func(context.Context, boil.ContextExecutor, *QuantityEntry) error

	quantityEntryQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	quantityEntryType                 = reflect.TypeOf(&QuantityEntry{})
	quantityEntryMapping              = queries.MakeStructMapping(quantityEntryType)
	quantityEntryPrimaryKeyMapping, _ = queries.BindMapping(quantityEntryType, quantityEntryMapping, quantityEntryPrimaryKeyColumns)
	quantityEntryInsertCacheMut       sync.RWMutex
	quantityEntryInsertCache          = make(map[string]insertCache)
	quantityEntryUpdateCacheMut       sync.RWMutex
	quantityEntryUpdateCache          = make(map[string]updateCache)
	quantityEntryUpsertCacheMut       sync.RWMutex
	quantityEntryUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var quantityEntryAfterSelectMu sync.Mutex
var quantityEntryAfterSelectHooks []QuantityEntryHook

var quantityEntryBeforeInsertMu sync.Mutex
var quantityEntryBeforeInsertHooks []QuantityEntryHook
var quantityEntryAfterInsertMu sync.Mutex
var quantityEntryAfterInsertHooks []QuantityEntryHook

var quantityEntryBeforeUpdateMu sync.Mutex
var quantityEntryBeforeUpdateHooks []QuantityEntryHook
var quantityEntryAfterUpdateMu sync.Mutex
var quantityEntryAfterUpdateHooks []QuantityEntryHook

var quantityEntryBeforeDeleteMu sync.Mutex
var quantityEntryBeforeDeleteHooks []QuantityEntryHook
var quantityEntryAfterDeleteMu sync.Mutex
var quantityEntryAfterDeleteHooks []QuantityEntryHook

var quantityEntryBeforeUpsertMu sync.Mutex
var quantityEntryBeforeUpsertHooks []QuantityEntryHook
var quantityEntryAfterUpsertMu sync.Mutex
var quantityEntryAfterUpsertHooks []QuantityEntryHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *QuantityEntry) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range quantityEntryAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *QuantityEntry) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range quantityEntryBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *QuantityEntry) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range quantityEntryAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *QuantityEntry) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range quantityEntryBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *QuantityEntry) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range quantityEntryAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *QuantityEntry) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range quantityEntryBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *QuantityEntry) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range quantityEntryAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *QuantityEntry) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range quantityEntryBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *QuantityEntry) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range quantityEntryAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddQuantityEntryHook registers your hook function for all future operations.
func AddQuantityEntryHook(hookPoint boil.HookPoint, quantityEntryHook QuantityEntryHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		quantityEntryAfterSelectMu.Lock()
		quantityEntryAfterSelectHooks = append(quantityEntryAfterSelectHooks, quantityEntryHook)
		quantityEntryAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		quantityEntryBeforeInsertMu.Lock()
		quantityEntryBeforeInsertHooks = append(quantityEntryBeforeInsertHooks, quantityEntryHook)
		quantityEntryBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		quantityEntryAfterInsertMu.Lock()
		quantityEntryAfterInsertHooks = append(quantityEntryAfterInsertHooks, quantityEntryHook)
		quantityEntryAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		quantityEntryBeforeUpdateMu.Lock()
		quantityEntryBeforeUpdateHooks = append(quantityEntryBeforeUpdateHooks, quantityEntryHook)
		quantityEntryBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		quantityEntryAfterUpdateMu.Lock()
		quantityEntryAfterUpdateHooks = append(quantityEntryAfterUpdateHooks, quantityEntryHook)
		quantityEntryAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		quantityEntryBeforeDeleteMu.Lock()
		quantityEntryBeforeDeleteHooks = append(quantityEntryBeforeDeleteHooks, quantityEntryHook)
		quantityEntryBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		quantityEntryAfterDeleteMu.Lock()
		quantityEntryAfterDeleteHooks = append(quantityEntryAfterDeleteHooks, quantityEntryHook)
		quantityEntryAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		quantityEntryBeforeUpsertMu.Lock()
		quantityEntryBeforeUpsertHooks = append(quantityEntryBeforeUpsertHooks, quantityEntryHook)
		quantityEntryBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		quantityEntryAfterUpsertMu.Lock()
		quantityEntryAfterUpsertHooks = append(quantityEntryAfterUpsertHooks, quantityEntryHook)
		quantityEntryAfterUpsertMu.Unlock()
	}
}

// One returns a single quantityEntry record from the query.
func (q quantityEntryQuery) One(ctx context.Context, exec boil.ContextExecutor) (*QuantityEntry, error) {
	o := &QuantityEntry{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for quantity_entries")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all QuantityEntry records from the query.
func (q quantityEntryQuery) All(ctx context.Context, exec boil.ContextExecutor) (QuantityEntrySlice, error) {
	var o []*QuantityEntry

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to QuantityEntry slice")
	}

	if len(quantityEntryAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all QuantityEntry records in the query.
func (q quantityEntryQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count quantity_entries rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q quantityEntryQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if quantity_entries exists")
	}

	return count > 0, nil
}

// Thing pointed to by the foreign key.
func (o *QuantityEntry) Thing(mods ...qm.QueryMod) thingQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.ThingID),
	}

	queryMods = append(queryMods, mods...)

	return Things(queryMods...)
}

// LoadThing allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (quantityEntryL) LoadThing(ctx context.Context, e boil.ContextExecutor, singular bool, maybeQuantityEntry interface{}, mods queries.Applicator) error {
	var slice []*QuantityEntry
	var object *QuantityEntry

	if singular {
		var ok bool
		object, ok = maybeQuantityEntry.(*QuantityEntry)
		if !ok {
			object = new(QuantityEntry)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeQuantityEntry)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeQuantityEntry))
			}
		}
	} else {
		s, ok := maybeQuantityEntry.(*[]*QuantityEntry)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeQuantityEntry)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeQuantityEntry))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &quantityEntryR{}
		}
		args[object.ThingID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &quantityEntryR{}
			}

			args[obj.ThingID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`things`),
		qm.WhereIn(`things.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Thing")
	}

	var resultSlice []*Thing
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Thing")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for things")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for things")
	}

	if len(thingAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Thing = foreign
		if foreign.R == nil {
			foreign.R = &thingR{}
		}
		foreign.R.QuantityEntries = append(foreign.R.QuantityEntries, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.ThingID == foreign.ID {
				local.R.Thing = foreign
				if foreign.R == nil {
					foreign.R = &thingR{}
				}
				foreign.R.QuantityEntries = append(foreign.R.QuantityEntries, local)
				break
			}
		}
	}

	return nil
}

// SetThing of the quantityEntry to the related item.
// Sets o.R.Thing to related.
// Adds o to related.R.QuantityEntries.
func (o *QuantityEntry) SetThing(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Thing) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"quantity_entries\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"thing_id"}),
		strmangle.WhereClause("\"", "\"", 2, quantityEntryPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.ThingID = related.ID
	if o.R == nil {
		o.R = &quantityEntryR{
			Thing: related,
		}
	} else {
		o.R.Thing = related
	}

	if related.R == nil {
		related.R = &thingR{
			QuantityEntries: QuantityEntrySlice{o},
		}
	} else {
		related.R.QuantityEntries = append(related.R.QuantityEntries, o)
	}

	return nil
}

// QuantityEntries retrieves all the records using an executor.
func QuantityEntries(mods ...qm.QueryMod) quantityEntryQuery {
	mods = append(mods, qm.From("\"quantity_entries\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"quantity_entries\".*"})
	}

	return quantityEntryQuery{q}
}

// FindQuantityEntry retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindQuantityEntry(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*QuantityEntry, error) {
	quantityEntryObj := &QuantityEntry{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"quantity_entries\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, quantityEntryObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from quantity_entries")
	}

	if err = quantityEntryObj.doAfterSelectHooks(ctx, exec); err != nil {
		return quantityEntryObj, err
	}

	return quantityEntryObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *QuantityEntry) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no quantity_entries provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(quantityEntryColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	quantityEntryInsertCacheMut.RLock()
	cache, cached := quantityEntryInsertCache[key]
	quantityEntryInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			quantityEntryAllColumns,
			quantityEntryColumnsWithDefault,
			quantityEntryColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(quantityEntryType, quantityEntryMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(quantityEntryType, quantityEntryMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"quantity_entries\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"quantity_entries\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into quantity_entries")
	}

	if !cached {
		quantityEntryInsertCacheMut.Lock()
		quantityEntryInsertCache[key] = cache
		quantityEntryInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the QuantityEntry.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *QuantityEntry) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	quantityEntryUpdateCacheMut.RLock()
	cache, cached := quantityEntryUpdateCache[key]
	quantityEntryUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			quantityEntryAllColumns,
			quantityEntryPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update quantity_entries, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"quantity_entries\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, quantityEntryPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(quantityEntryType, quantityEntryMapping, append(wl, quantityEntryPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update quantity_entries row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for quantity_entries")
	}

	if !cached {
		quantityEntryUpdateCacheMut.Lock()
		quantityEntryUpdateCache[key] = cache
		quantityEntryUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q quantityEntryQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for quantity_entries")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for quantity_entries")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o QuantityEntrySlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), quantityEntryPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"quantity_entries\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, quantityEntryPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in quantityEntry slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all quantityEntry")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *QuantityEntry) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no quantity_entries provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(quantityEntryColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	quantityEntryUpsertCacheMut.RLock()
	cache, cached := quantityEntryUpsertCache[key]
	quantityEntryUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			quantityEntryAllColumns,
			quantityEntryColumnsWithDefault,
			quantityEntryColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			quantityEntryAllColumns,
			quantityEntryPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert quantity_entries, could not build update column list")
		}

		ret := strmangle.SetComplement(quantityEntryAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(quantityEntryPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert quantity_entries, could not build conflict column list")
			}

			conflict = make([]string, len(quantityEntryPrimaryKeyColumns))
			copy(conflict, quantityEntryPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"quantity_entries\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(quantityEntryType, quantityEntryMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(quantityEntryType, quantityEntryMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert quantity_entries")
	}

	if !cached {
		quantityEntryUpsertCacheMut.Lock()
		quantityEntryUpsertCache[key] = cache
		quantityEntryUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single QuantityEntry record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *QuantityEntry) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no QuantityEntry provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), quantityEntryPrimaryKeyMapping)
	sql := "DELETE FROM \"quantity_entries\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from quantity_entries")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for quantity_entries")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q quantityEntryQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no quantityEntryQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from quantity_entries")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for quantity_entries")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o QuantityEntrySlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(quantityEntryBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), quantityEntryPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"quantity_entries\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, quantityEntryPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from quantityEntry slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for quantity_entries")
	}

	if len(quantityEntryAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *QuantityEntry) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindQuantityEntry(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *QuantityEntrySlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := QuantityEntrySlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), quantityEntryPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"quantity_entries\".* FROM \"quantity_entries\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, quantityEntryPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in QuantityEntrySlice")
	}

	*o = slice

	return nil
}

// QuantityEntryExists checks if the QuantityEntry row exists.
func QuantityEntryExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"quantity_entries\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if quantity_entries exists")
	}

	return exists, nil
}

// Exists checks if the QuantityEntry row exists.
func (o *QuantityEntry) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return QuantityEntryExists(ctx, exec, o.ID)
}
